query GetRoleDetails($name: String!) {
	role(name: $name) {
		id
		name
		displayName
		description
		hierarchy
		isRestricted
		isActive
	}
	rolePermissions(role: $name) {
		resource
		action
		scope
		effect
	}
}
