query UserManager($userId: String!) {
    users(query: {id: $userId}) {
        ...Fragment_PlayerManagerUsers
        ...Fragment_UserAccounts
        id
        username
        players {
            id
            game {
                name
                id
            }
        }
    }
    games {
        ...Fragment_PlayerManagerGames
    }
}