import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TypeormBootstrapService } from './typeorm-bootstrap/typeorm-bootstrap.service';
import { SprocketConfigService } from '@sprocketbot/lib';

import {
	GameEntity,
	GameModeEntity,
	RoleEntity,
	SeatEntity,
	SkillGroupEntity,
	FranchiseEntity,
	FranchiseSeatAssignmentEntity,
	ClubEntity,
	ClubSeatAssignmentEntity,
	TeamEntity,
	TeamSeatAssignmentEntity,
	MatchEntity,
	ScrimEntity,
	FixtureEntity,
	PlayerEntity,
	PlayerStatEntity,
	RoundEntity,
	ScheduleGroupEntity,
	ScheduleGroupTypeEntity,
	UserEntity,
	UserAuthAccountEntity,
	GameRepository,
	GameModeRepository,
	RoleRepository,
	SeatRepository,
	SkillGroupRepository,
	FranchiseRepository,
	FranchiseSeatAssignmentRepository,
	ClubRepository,
	ClubSeatAssignmentRepository,
	TeamRepository,
	TeamSeatAssignmentRepository,
	MatchRepository,
	ScrimRepository,
	FixtureRepository,
	PlayerRepository,
	PlayerStatRepository,
	RoundRepository,
	ScheduleGroupRepository,
	ScheduleGroupTypeRepository,
	UserRepository,
	UserAuthAccountRepository,
	LogsEntity,
	MetricsEntity,
	LogsRepository,
	MetricsRepository
} from './internal';

@Module({
	imports: [
		TypeOrmModule.forRootAsync({
			inject: [SprocketConfigService],
			useClass: TypeormBootstrapService
		}),
		TypeOrmModule.forFeature([
			GameEntity,
			GameModeEntity,
			RoleEntity,
			SeatEntity,
			SkillGroupEntity,
			FranchiseEntity,
			FranchiseSeatAssignmentEntity,
			ClubEntity,
			ClubSeatAssignmentEntity,
			TeamEntity,
			TeamSeatAssignmentEntity,
			MatchEntity,
			ScrimEntity,
			FixtureEntity,
			PlayerEntity,
			PlayerStatEntity,
			RoundEntity,
			ScheduleGroupEntity,
			ScheduleGroupTypeEntity,
			UserEntity,
			UserAuthAccountEntity,
			LogsEntity,
			MetricsEntity
		])
	],
	providers: [
		GameRepository,
		GameModeRepository,
		RoleRepository,
		SeatRepository,
		SkillGroupRepository,
		FranchiseRepository,
		FranchiseSeatAssignmentRepository,
		ClubRepository,
		ClubSeatAssignmentRepository,
		TeamRepository,
		TeamSeatAssignmentRepository,
		MatchRepository,
		ScrimRepository,
		FixtureRepository,
		PlayerRepository,
		PlayerStatRepository,
		RoundRepository,
		ScheduleGroupRepository,
		ScheduleGroupTypeRepository,
		UserRepository,
		UserAuthAccountRepository,
		LogsRepository,
		MetricsRepository
	],
	exports: [
		GameRepository,
		GameModeRepository,
		RoleRepository,
		SeatRepository,
		SkillGroupRepository,
		FranchiseRepository,
		FranchiseSeatAssignmentRepository,
		ClubRepository,
		ClubSeatAssignmentRepository,
		TeamRepository,
		TeamSeatAssignmentRepository,
		MatchRepository,
		ScrimRepository,
		FixtureRepository,
		PlayerRepository,
		PlayerStatRepository,
		RoundRepository,
		ScheduleGroupRepository,
		ScheduleGroupTypeRepository,
		UserRepository,
		UserAuthAccountRepository,
		LogsRepository,
		MetricsRepository
	]
})
export class DbModule { }
