# We can access environment variables in our config file
baseUrl: ${BASE_URL}
secure: ${SSL:false}

service:
  name: '${SERVICE_NAME}'

auth:
  jwt:
    secret: '${AUTH_JWT_SECRET:localhost}'
    expiry: '${AUTH_JWT_EXPIRY:259200000}' # Default is 72h
  discord:
    clientId: '${AUTH_DISCORD_CLIENT_ID}'
    secret: '${AUTH_DISCORD_SECRET}'
    botToken: '${AUTH_DISCORD_BOT_TOKEN}'
  steam:
    apiKey: '${AUTH_STEAM_API_KEY}'

frontend:
  url: '${BASE_URL}:${LISTEN_PORT}'
  callback: '${BASE_URL}:${LISTEN_PORT}/auth/callback'

pg:
  host: '${PG_HOST:postgres}'
  username: '${PG_USER:postgres}'
  password: '${PG_PASS:postgres}'
  port: '${PG_PORT:5432}'
  database: '${PG_DATABASE:postgres}'
  cache: '${PG_CACHE:true}'

redis:
  hostname: '${REDIS_HOST:redis}'
  port: '${REDIS_PORT:6379}'

initialAdmins:
  - 'shuckle'
  - 'nigelthornbrake'
  - '.hermod.'

amqp:
  url: '${AMQP_URL}'

s3:
  app_key: '${S3_APP_KEY}'
  key_id: '${S3_KEY_ID}'
  key_name: '${S3_KEY_NAME}'
  endpoint: '${S3_ENDPOINT}'
  bucket: '${S3_BUCKET}'
  prefix: '${S3_PREFIX}'