version: "3.9"

services:
  rmq:
    image: rabbitmq:3.9.14-management-alpine
    volumes:
      - "./.data/rmq:/var/lib/rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672 # management UI

  redis:
    image: redislabs/rejson:2.0.7
    volumes:
      - "./.data/redis:/data"
    command: --requirepass $SPR_REDIS_PASSWORD --loadmodule "/usr/lib/redis/modules/rejson.so" --loadmodule "/usr/lib/redis/modules/redisearch.so"
    ports:
      - 6379:6379

  postgres:
    image: timescale/timescaledb:2.6.0-pg13
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: $SPR_DB_USER
      POSTGRES_PASSWORD: $SPR_DB_PASSWORD
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2022-04-30T22-23-53Z
    volumes:
      - "./.data/minio:/data"
    environment:
      # TODO set up access token
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    entrypoint: sh 
    command: -c 'mkdir -p /data/image_generation && mkdir -p /data/replays && minio server /data --console-address :9001'
    ports:
      - 9000:9000
      - 9001:9001 # management UI

  influx:
    image: influxdb:2.1-alpine
    volumes:
      - "./.data/influx:/var/lib/influxdb2"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ORG: $SPR_INFLUX_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $SPR_INFLUX_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $SPR_INFLUX_TOKEN
      DOCKER_INFLUXDB_INIT_USERNAME: sprocket
      DOCKER_INFLUXDB_INIT_PASSWORD: sprocket
    ports:
      - 8086:8086
