import {MigrationInterface, QueryRunner} from "typeorm";

export class Automigration1651454689960 implements MigrationInterface {
    name = 'Automigration1651454689960'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sprocket"."action" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "description" character varying NOT NULL, "code" character varying NOT NULL, CONSTRAINT "PK_2d9db9cf5edfbbae74eb56e3a39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."permission_bearer" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_cb6f2fab0455d9f63cb5959796d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_leadership_role" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "ordinal" integer NOT NULL, "bearerId" integer, CONSTRAINT "REL_7e2b3f74d7fd48a30ef15aec1d" UNIQUE ("bearerId"), CONSTRAINT "PK_12c7ebb2933e6f6cfacd9ce6819" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_configuration_allowed_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "pattern" boolean NOT NULL, "keyId" integer, CONSTRAINT "PK_b851b6f8a46fd64e09013686826" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_configuration_key" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "default" character varying NOT NULL, CONSTRAINT "PK_cf65903b8818831b24f95e8ad5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_configuration_value" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "value" character varying NOT NULL, "organizationId" integer, "keyId" integer, CONSTRAINT "PK_e422ea050160eed5c772e9baf5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."verbiage_code" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "default" character varying NOT NULL, CONSTRAINT "PK_54ac3dfd3bbc7186f7b50413451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."verbiage" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "term" character varying NOT NULL, "organizationId" integer, "codeId" integer, CONSTRAINT "UQ_676fbd9092ca76fd1a362084d30" UNIQUE ("organizationId", "codeId"), CONSTRAINT "PK_45dfb737927c4ccb1c6c8e8c80c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."invalidation" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "description" character varying NOT NULL, "favorsHomeTeam" boolean NOT NULL, CONSTRAINT "PK_70af63d2129081c444aca207424" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."round" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "homeWon" boolean NOT NULL, "roundStats" jsonb NOT NULL, "isDummy" boolean NOT NULL DEFAULT false, "matchId" integer, "invalidationId" integer, CONSTRAINT "PK_34bd959f3f4a90eb86e4ae24d2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."match" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "isDummy" boolean NOT NULL DEFAULT false, "matchParentId" integer, CONSTRAINT "REL_cdacd386dc74af4e9cb1221304" UNIQUE ("matchParentId"), CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."scrim_meta" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "parentId" integer, CONSTRAINT "REL_0f9e7c4013624a6c635dd9c855" UNIQUE ("parentId"), CONSTRAINT "PK_e846097b793959d6729ad330ca0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."game_mode" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, "teamSize" integer NOT NULL, "teamCount" integer NOT NULL, "gameId" integer, CONSTRAINT "PK_ef9a2ad96f7bcea1655cd17e575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."scheduled_event" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "description" character varying NOT NULL, "start" TIMESTAMP NOT NULL, "end" TIMESTAMP, "url" character varying, "hostId" integer, "gameModeId" integer, "gameId" integer, CONSTRAINT "PK_59a1f1e0d902729bdfe3d02c089" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."match_parent" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "eventId" integer, CONSTRAINT "PK_18e2f07b1af7ee65de551065655" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."schedule_fixture" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "scheduleGroupId" integer, "homeFranchiseId" integer, "awayFranchiseId" integer, CONSTRAINT "PK_1a2b3b95a8c8fb82a7c91b1c2e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."schedule_group" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "start" TIMESTAMP NOT NULL, "end" TIMESTAMP NOT NULL, "description" character varying, "typeId" integer, "gameId" integer, "parentGroupId" integer, CONSTRAINT "PK_b9579e4a3a46e2afdae0b757048" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."schedule_group_type" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "code" character varying NOT NULL, "organizationId" integer, CONSTRAINT "PK_33f1d34f327abe56f6b1a3f716a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_mottos" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "motto" character varying NOT NULL, "organizationId" integer, CONSTRAINT "PK_7522c2d99d481e6b32e0df5af30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "description" character varying NOT NULL, "websiteUrl" character varying NOT NULL DEFAULT '', "primaryColor" character varying NOT NULL, "secondaryColor" character varying NOT NULL, "logoUrl" character varying, CONSTRAINT "PK_a459f7af77cb9a0fd82286f661a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."pronouns" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "subjectPronoun" character varying NOT NULL, "objectPronoun" character varying NOT NULL, "possessiveAdjective" character varying NOT NULL, "possessivePronoun" character varying NOT NULL, "reflexivePronoun" character varying NOT NULL, "organizationId" integer, CONSTRAINT "PK_5aa472abefd4f380bdf044f8f45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "organizationProfileId" integer, CONSTRAINT "REL_0b10df9cf789464c09784b32e4" UNIQUE ("organizationProfileId"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."enabled_feature" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "featureId" integer, "organizationId" integer, CONSTRAINT "PK_2df4ccb03272fc463dc141f4cf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."feature" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_03930932f909ca4be8e33d16a2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."game_feature" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "gameId" integer, "featureId" integer, CONSTRAINT "PK_a10da673ec6ba61326a995d2319" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."member_platform_account" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "platformAccountId" character varying NOT NULL, "memberId" integer, "platformId" integer, CONSTRAINT "PK_2ba5187498e03bc444a639acf9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."platform" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_c33d6abeebd214bd2850bfd6b8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."game" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying NOT NULL, CONSTRAINT "PK_352a30652cd352f552fef73dec5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_group_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "PK_7fea2b0af9a1fb03d2ad152e41d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_group_type" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_f47e132453dbb400a64b3c207e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_group" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "parentGroupId" integer, "typeId" integer, "profileId" integer, CONSTRAINT "REL_1b6a651f78ce0209633237fe94" UNIQUE ("profileId"), CONSTRAINT "PK_bf0cfd2dc210b601af0829595bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_group_assignment" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "franchiseId" integer, "groupId" integer, "gameId" integer, CONSTRAINT "PK_0c44b17a887d5d3c6879bff36a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying NOT NULL, "code" character varying NOT NULL, CONSTRAINT "PK_56cafce34b1b79ff64cad88f5e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_staff_role" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "ordinal" integer NOT NULL, "bearerId" integer, "gameId" integer, CONSTRAINT "REL_075a700938ebdcaef94e5672d5" UNIQUE ("bearerId"), CONSTRAINT "PK_0129cc5988c389e957cb69a3857" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_staff_seat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "roleId" integer, CONSTRAINT "PK_76aef6134498112663663afd38b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_staff_appointment" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "franchiseId" integer, "memberId" integer, "seatId" integer, CONSTRAINT "PK_a7a901553d89304317efe6ac7c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_0d92e63ee108403e7f251ef8e35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."game_skill_group_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_587c31f49968a771096c54befc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."roster_role" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, "gameId" integer, "skillGroupId" integer, "organizationId" integer, CONSTRAINT "PK_a9a81791c44af44afa79508d776" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."team" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "franchiseId" integer, "skillGroupId" integer, CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."roster_slot" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "roleId" integer, "teamId" integer, CONSTRAINT "PK_0231f0547cb1c1cd9e94ed1a8d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."player" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "salary" integer NOT NULL, "memberId" integer, "skillGroupId" integer, CONSTRAINT "PK_65edadc946a7faf4b638d5e8885" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."roster_role_use_limits" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "perMode" integer NOT NULL, "total" integer NOT NULL, "groupTypeId" integer, CONSTRAINT "PK_bacf5593cd89566c21dcb376bc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."game_skill_group" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, "ordinal" integer NOT NULL, "salaryCap" integer NOT NULL, "profileId" integer, "roleUseLimitsId" integer, CONSTRAINT "REL_adb40c3fbfade82e3293f62dd3" UNIQUE ("profileId"), CONSTRAINT "REL_30dc9ad00173ae281344068f93" UNIQUE ("roleUseLimitsId"), CONSTRAINT "PK_3aa04cc5a2393be8f8c55aeac22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."roster_role_usage" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "teamId" integer, "playerId" integer, "rosterRoleId" integer, "matchId" integer, CONSTRAINT "PK_1761040d29845c0653dd6c5aebc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."approval" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "notes" character varying NOT NULL, "isApproved" boolean NOT NULL DEFAULT false, "approvedById" integer, CONSTRAINT "PK_97bfd1cd9dff3c1302229da6b5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."photo" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "url" character varying, "approvalId" integer, CONSTRAINT "REL_3356374afaba354ff1838e0682" UNIQUE ("approvalId"), CONSTRAINT "PK_723fa50bf70dcfd06fb5a44d4ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."member_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "pronounsId" integer, "profilePictureId" integer, CONSTRAINT "REL_65fe3ee2b2ebf66ddb515a4e5d" UNIQUE ("profilePictureId"), CONSTRAINT "PK_157ca6e25e9cbd657a2302fb12d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."member" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "discordId" character varying NOT NULL, "profileId" integer, "organizationId" integer, CONSTRAINT "UQ_cb0df66149e4aab52ac820afbce" UNIQUE ("discordId"), CONSTRAINT "REL_b9bb63f508aa958461750fb21d" UNIQUE ("profileId"), CONSTRAINT "PK_97cbbe986ce9d14ca5894fdc072" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_leadership_appointment" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "franchiseId" integer, "memberId" integer, "seatId" integer, CONSTRAINT "PK_35a420669a4f2bd0394f0133e64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."franchise_leadership_seat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "roleId" integer, CONSTRAINT "PK_8ad62cc5dbbcef96db6cb253451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_staff_role" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "ordinal" integer NOT NULL, "bearerId" integer, CONSTRAINT "REL_8dceec978102c8fda542d208bd" UNIQUE ("bearerId"), CONSTRAINT "PK_4ddd8a764f33ffd0810bfe0752d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_staff_team" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "ordinal" integer NOT NULL, "bearerId" integer, CONSTRAINT "REL_9d86ca7e7759f11d2b6d4a9924" UNIQUE ("bearerId"), CONSTRAINT "PK_03225eddd768c3dc30bd26e1dd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_staff_position" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "roleId" integer, "teamId" integer, "bearerId" integer, CONSTRAINT "REL_f62c50a4c0727ac36c7483ad7b" UNIQUE ("bearerId"), CONSTRAINT "PK_b013d45619e65dfa05365bc8941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."organization_staff_seat" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "memberId" integer, "positionId" integer, CONSTRAINT "PK_208d34206c7fde1ef8c5a8ce279" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."permission" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "actionId" integer, "bearerId" integer, CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."sprocket_configuration" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "key" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_ea7bda0dfbccb1071e3932e0d1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."draft_selection" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "draftPickId" integer, "playerId" integer, CONSTRAINT "REL_b70237128e7538a537c913cd70" UNIQUE ("draftPickId"), CONSTRAINT "PK_dbc11a61d790550f59e41749219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."draft_pick" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ordinal" integer NOT NULL, "round" integer NOT NULL, "originalTeamId" integer, "executingTeamId" integer, "skillGroupId" integer, "scheduleGroupId" integer, CONSTRAINT "PK_42d69ba590c808f072cb117be15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "sprocket"."user_roles_accounttype_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "sprocket"."user_roles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "accountType" "sprocket"."user_roles_accounttype_enum" NOT NULL, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."user_profile" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "email" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', CONSTRAINT "PK_f44d0cd18cfd80b0fed7806c3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "sprocket"."user_type_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "sprocket"."user" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "sprocket"."user_type_enum" array, "userProfileId" integer, CONSTRAINT "REL_2ffc8d3455097079866bfca4d4" UNIQUE ("userProfileId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "sprocket"."user_authentication_account_accounttype_enum" AS ENUM('DISCORD', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "sprocket"."user_authentication_account" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "accountId" character varying NOT NULL, "accountType" "sprocket"."user_authentication_account_accounttype_enum" NOT NULL, "oauthToken" character varying, "userId" integer, CONSTRAINT "UserAccounts" UNIQUE ("accountId", "accountType"), CONSTRAINT "PK_bd8e58076a243f05dd2e7e1861b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."eligibility_data" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "points" integer NOT NULL, "matchParentId" integer, "playerId" integer, CONSTRAINT "PK_7adcd47caa5fc407a9ffd258c2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."team_stat_line" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "stats" jsonb NOT NULL, "teamName" character varying NOT NULL, "teamId" integer, "roundId" integer, CONSTRAINT "PK_1607a63fa4976a3c4478ac0c678" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."player_stat_line" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "stats" jsonb NOT NULL, "isHome" boolean NOT NULL, "roundId" integer, "teamStatsId" integer, CONSTRAINT "PK_c3b04960f5894882ff6e1104152" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprocket"."feature_dependency" ("feature_id" integer NOT NULL, "dependency_id" integer NOT NULL, CONSTRAINT "PK_1e69eb60353f60ccecbb89a8a14" PRIMARY KEY ("feature_id", "dependency_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb3d3008100cb2e46bcc932930" ON "sprocket"."feature_dependency" ("feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_156686114faf2216039503a310" ON "sprocket"."feature_dependency" ("dependency_id") `);
        await queryRunner.query(`CREATE TABLE "sprocket"."game_platform" ("gameId" integer NOT NULL, "platformId" integer NOT NULL, CONSTRAINT "PK_1dc0ba06fc44ca9f53d3f086050" PRIMARY KEY ("gameId", "platformId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c5a64b96aa786ca91da4a91715" ON "sprocket"."game_platform" ("gameId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b36a6dc7f05e2250f6789655ff" ON "sprocket"."game_platform" ("platformId") `);
        await queryRunner.query(`ALTER TABLE "mledb"."season" ALTER COLUMN "week_length" SET DEFAULT 7`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ALTER COLUMN "chain" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ALTER COLUMN "overtime_seconds" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "salary" SET DEFAULT '-1.0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "peak_mmr" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "salary" SET DEFAULT '-1.0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "peak_mmr" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_role" ADD CONSTRAINT "FK_7e2b3f74d7fd48a30ef15aec1de" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_allowed_value" ADD CONSTRAINT "FK_cb2355f94f406359ecee9637ddd" FOREIGN KEY ("keyId") REFERENCES "sprocket"."organization_configuration_key"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_value" ADD CONSTRAINT "FK_67dce788f993dd716050261f7a9" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_value" ADD CONSTRAINT "FK_4583a3c108de67e025d108a63fb" FOREIGN KEY ("keyId") REFERENCES "sprocket"."organization_configuration_key"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."verbiage" ADD CONSTRAINT "FK_239465739873e831f435615d96d" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."verbiage" ADD CONSTRAINT "FK_8e06145c03deef3a10b5a0848fd" FOREIGN KEY ("codeId") REFERENCES "sprocket"."verbiage_code"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."round" ADD CONSTRAINT "FK_7f3ebe2c9b6582d68973dd1de22" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."round" ADD CONSTRAINT "FK_70694bc051fc00d714b6dfc07bd" FOREIGN KEY ("invalidationId") REFERENCES "sprocket"."invalidation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_cdacd386dc74af4e9cb12213049" FOREIGN KEY ("matchParentId") REFERENCES "sprocket"."match_parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scrim_meta" ADD CONSTRAINT "FK_0f9e7c4013624a6c635dd9c8558" FOREIGN KEY ("parentId") REFERENCES "sprocket"."match_parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_mode" ADD CONSTRAINT "FK_1591079e6dddb2d90e90e94fdc2" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" ADD CONSTRAINT "FK_0989bdf13136d091c2630a7f51b" FOREIGN KEY ("hostId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" ADD CONSTRAINT "FK_8c86d4dba2f71f4c6a235fb28a7" FOREIGN KEY ("gameModeId") REFERENCES "sprocket"."game_mode"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" ADD CONSTRAINT "FK_3c854126efbbf608a2682cffdea" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."match_parent" ADD CONSTRAINT "FK_853b1e768cb493c250e7c7a23f1" FOREIGN KEY ("eventId") REFERENCES "sprocket"."scheduled_event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" ADD CONSTRAINT "FK_e7a8e560ca504d498a245185afd" FOREIGN KEY ("scheduleGroupId") REFERENCES "sprocket"."schedule_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" ADD CONSTRAINT "FK_78a0874f503f718434346afedc4" FOREIGN KEY ("homeFranchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" ADD CONSTRAINT "FK_61ef1b6aff93c92ca17d2c64e1d" FOREIGN KEY ("awayFranchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" ADD CONSTRAINT "FK_6b2836d4ed4dff841b40d9bc1ee" FOREIGN KEY ("typeId") REFERENCES "sprocket"."schedule_group_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" ADD CONSTRAINT "FK_ff8b23c2e61c484aec8bc1e3c6d" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" ADD CONSTRAINT "FK_d1884396b8fe01bfef7c6166404" FOREIGN KEY ("parentGroupId") REFERENCES "sprocket"."schedule_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group_type" ADD CONSTRAINT "FK_fb786f931ab2a1db8b6f8785940" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_mottos" ADD CONSTRAINT "FK_ce5e00022caab1c1e19dd7e040e" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."pronouns" ADD CONSTRAINT "FK_ab64820e64338ba71059368d8ba" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization" ADD CONSTRAINT "FK_0b10df9cf789464c09784b32e4c" FOREIGN KEY ("organizationProfileId") REFERENCES "sprocket"."organization_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."enabled_feature" ADD CONSTRAINT "FK_c8a0693a644e1fd962f90e0654e" FOREIGN KEY ("featureId") REFERENCES "sprocket"."game_feature"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."enabled_feature" ADD CONSTRAINT "FK_64c0a133010141ea04efdf3f9b7" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_feature" ADD CONSTRAINT "FK_ac6faff211b59159157e52efeae" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_feature" ADD CONSTRAINT "FK_78074e38ced12d7aced41ebd67c" FOREIGN KEY ("featureId") REFERENCES "sprocket"."feature"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_platform_account" ADD CONSTRAINT "FK_f790210c8106972edb55c49f572" FOREIGN KEY ("memberId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_platform_account" ADD CONSTRAINT "FK_f7455aa82715ab0e817f8e6ade3" FOREIGN KEY ("platformId") REFERENCES "sprocket"."platform"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" ADD CONSTRAINT "FK_c5a9c04afe2cea55b9523321cbb" FOREIGN KEY ("parentGroupId") REFERENCES "sprocket"."franchise_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" ADD CONSTRAINT "FK_adb75cdee1e4c1c8740aeab36ca" FOREIGN KEY ("typeId") REFERENCES "sprocket"."franchise_group_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" ADD CONSTRAINT "FK_1b6a651f78ce0209633237fe945" FOREIGN KEY ("profileId") REFERENCES "sprocket"."franchise_group_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" ADD CONSTRAINT "FK_20184f6e40943fcbff3f2a1032e" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" ADD CONSTRAINT "FK_2c386e796af4d426f9c10678801" FOREIGN KEY ("groupId") REFERENCES "sprocket"."franchise_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" ADD CONSTRAINT "FK_b73ec09ebdaf90554462be9b3da" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_role" ADD CONSTRAINT "FK_075a700938ebdcaef94e5672d57" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_role" ADD CONSTRAINT "FK_fb3577db7eaf1d3698f9bab3337" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_seat" ADD CONSTRAINT "FK_a727550401c780f3d354601f1a4" FOREIGN KEY ("roleId") REFERENCES "sprocket"."franchise_staff_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" ADD CONSTRAINT "FK_ca08f0936b3922b98f999cee51f" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" ADD CONSTRAINT "FK_c42330f89150285a50e2f262e49" FOREIGN KEY ("memberId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" ADD CONSTRAINT "FK_c826d7607c5ca571346a6b52af1" FOREIGN KEY ("seatId") REFERENCES "sprocket"."franchise_staff_seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" ADD CONSTRAINT "FK_f0895013e2d4e16ca402f8aea7e" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" ADD CONSTRAINT "FK_4d98bca47aa0b1d3f39e0b54d16" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."game_skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" ADD CONSTRAINT "FK_7749e8dcc3f306fd33e9454fc36" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team" ADD CONSTRAINT "FK_652e04e862dac0c611e6a929ab3" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team" ADD CONSTRAINT "FK_0cbb30ed058102b0f260e911e3c" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."game_skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_slot" ADD CONSTRAINT "FK_5dc0fe96b415c76b42bf86c24d4" FOREIGN KEY ("roleId") REFERENCES "sprocket"."roster_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_slot" ADD CONSTRAINT "FK_fa375ed496bbf66579f161992fa" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player" ADD CONSTRAINT "FK_40e1ded9fbf4f2d9a6fcb9616a3" FOREIGN KEY ("memberId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player" ADD CONSTRAINT "FK_622bd2e2975785c536a74754290" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."game_skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_use_limits" ADD CONSTRAINT "FK_4463e23dc3f6abce154bf3596f0" FOREIGN KEY ("groupTypeId") REFERENCES "sprocket"."schedule_group_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_skill_group" ADD CONSTRAINT "FK_adb40c3fbfade82e3293f62dd31" FOREIGN KEY ("profileId") REFERENCES "sprocket"."game_skill_group_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_skill_group" ADD CONSTRAINT "FK_30dc9ad00173ae281344068f932" FOREIGN KEY ("roleUseLimitsId") REFERENCES "sprocket"."roster_role_use_limits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" ADD CONSTRAINT "FK_9fecdc70cde169c58d50bd60a98" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" ADD CONSTRAINT "FK_cb36315fa8d2eb02702153b579a" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" ADD CONSTRAINT "FK_6b96821a50975de3b039b64b7eb" FOREIGN KEY ("rosterRoleId") REFERENCES "sprocket"."roster_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" ADD CONSTRAINT "FK_2da59aebf7ccfc171d65aad6093" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."approval" ADD CONSTRAINT "FK_22f5123d3c19de9eaf7f3998a5b" FOREIGN KEY ("approvedById") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."photo" ADD CONSTRAINT "FK_3356374afaba354ff1838e0682b" FOREIGN KEY ("approvalId") REFERENCES "sprocket"."approval"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_profile" ADD CONSTRAINT "FK_afac34d97905cc53ae5e1b91b1d" FOREIGN KEY ("pronounsId") REFERENCES "sprocket"."pronouns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_profile" ADD CONSTRAINT "FK_65fe3ee2b2ebf66ddb515a4e5d1" FOREIGN KEY ("profilePictureId") REFERENCES "sprocket"."photo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD CONSTRAINT "FK_b9bb63f508aa958461750fb21db" FOREIGN KEY ("profileId") REFERENCES "sprocket"."member_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD CONSTRAINT "FK_8122e5920a29af5ef76e2e2ff62" FOREIGN KEY ("organizationId") REFERENCES "sprocket"."organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" ADD CONSTRAINT "FK_3ce0477eaed1b25d7031b5ac980" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" ADD CONSTRAINT "FK_aaa54ed884e4c3f6ec3187afcc6" FOREIGN KEY ("memberId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" ADD CONSTRAINT "FK_722a390774c594b1af95dc13b54" FOREIGN KEY ("seatId") REFERENCES "sprocket"."franchise_leadership_seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_seat" ADD CONSTRAINT "FK_25e87db7d4b12006318f64fa302" FOREIGN KEY ("roleId") REFERENCES "sprocket"."franchise_leadership_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_role" ADD CONSTRAINT "FK_8dceec978102c8fda542d208bd1" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_team" ADD CONSTRAINT "FK_9d86ca7e7759f11d2b6d4a9924d" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" ADD CONSTRAINT "FK_39b293f9c8e2bb2a5c26f7a6523" FOREIGN KEY ("roleId") REFERENCES "sprocket"."organization_staff_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" ADD CONSTRAINT "FK_36d1cb7c0206190cdea231f9c39" FOREIGN KEY ("teamId") REFERENCES "sprocket"."organization_staff_team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" ADD CONSTRAINT "FK_f62c50a4c0727ac36c7483ad7b2" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_seat" ADD CONSTRAINT "FK_4915e1817be2bc11b403d3f1e1a" FOREIGN KEY ("memberId") REFERENCES "sprocket"."member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_seat" ADD CONSTRAINT "FK_58ec0736cc3c2004c73747d8e34" FOREIGN KEY ("positionId") REFERENCES "sprocket"."organization_staff_position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."permission" ADD CONSTRAINT "FK_54b459f3ffe8a2420c1bb0aea5a" FOREIGN KEY ("actionId") REFERENCES "sprocket"."action"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."permission" ADD CONSTRAINT "FK_c9d7f25e5a6cc7a117f2eb7f153" FOREIGN KEY ("bearerId") REFERENCES "sprocket"."permission_bearer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_selection" ADD CONSTRAINT "FK_b70237128e7538a537c913cd706" FOREIGN KEY ("draftPickId") REFERENCES "sprocket"."draft_pick"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_selection" ADD CONSTRAINT "FK_dedab1017fb256df016a2bab002" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" ADD CONSTRAINT "FK_3c67219849b075794b044df64bf" FOREIGN KEY ("originalTeamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" ADD CONSTRAINT "FK_6879a34afad6535e182a0a747b5" FOREIGN KEY ("executingTeamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" ADD CONSTRAINT "FK_2d58976a00f8a93f42a0a2336a2" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."game_skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" ADD CONSTRAINT "FK_e730d058a8c9ed3d18fc3b47c1b" FOREIGN KEY ("scheduleGroupId") REFERENCES "sprocket"."schedule_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."user" ADD CONSTRAINT "FK_2ffc8d3455097079866bfca4d47" FOREIGN KEY ("userProfileId") REFERENCES "sprocket"."user_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."user_authentication_account" ADD CONSTRAINT "FK_095432105c4860d594fd9545c47" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."eligibility_data" ADD CONSTRAINT "FK_2691d44acf1452860b42885dcc2" FOREIGN KEY ("matchParentId") REFERENCES "sprocket"."match_parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."eligibility_data" ADD CONSTRAINT "FK_0f100ba2c2a7d456b3021b5dbd0" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team_stat_line" ADD CONSTRAINT "FK_c3054b95f3d5bf9ce44d02831b1" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team_stat_line" ADD CONSTRAINT "FK_3971333fea8eb2997697e791e8a" FOREIGN KEY ("roundId") REFERENCES "sprocket"."round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player_stat_line" ADD CONSTRAINT "FK_db402eaf1283ff74a755ba1ee5c" FOREIGN KEY ("roundId") REFERENCES "sprocket"."round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player_stat_line" ADD CONSTRAINT "FK_258531c49b53cc13684ea0d4b74" FOREIGN KEY ("teamStatsId") REFERENCES "sprocket"."team_stat_line"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprocket"."feature_dependency" ADD CONSTRAINT "FK_cb3d3008100cb2e46bcc9329303" FOREIGN KEY ("feature_id") REFERENCES "sprocket"."feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sprocket"."feature_dependency" ADD CONSTRAINT "FK_156686114faf2216039503a3100" FOREIGN KEY ("dependency_id") REFERENCES "sprocket"."feature"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_platform" ADD CONSTRAINT "FK_c5a64b96aa786ca91da4a917156" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_platform" ADD CONSTRAINT "FK_b36a6dc7f05e2250f6789655ffd" FOREIGN KEY ("platformId") REFERENCES "sprocket"."platform"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sprocket"."game_platform" DROP CONSTRAINT "FK_b36a6dc7f05e2250f6789655ffd"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_platform" DROP CONSTRAINT "FK_c5a64b96aa786ca91da4a917156"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."feature_dependency" DROP CONSTRAINT "FK_156686114faf2216039503a3100"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."feature_dependency" DROP CONSTRAINT "FK_cb3d3008100cb2e46bcc9329303"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player_stat_line" DROP CONSTRAINT "FK_258531c49b53cc13684ea0d4b74"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player_stat_line" DROP CONSTRAINT "FK_db402eaf1283ff74a755ba1ee5c"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team_stat_line" DROP CONSTRAINT "FK_3971333fea8eb2997697e791e8a"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team_stat_line" DROP CONSTRAINT "FK_c3054b95f3d5bf9ce44d02831b1"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."eligibility_data" DROP CONSTRAINT "FK_0f100ba2c2a7d456b3021b5dbd0"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."eligibility_data" DROP CONSTRAINT "FK_2691d44acf1452860b42885dcc2"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."user_authentication_account" DROP CONSTRAINT "FK_095432105c4860d594fd9545c47"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."user" DROP CONSTRAINT "FK_2ffc8d3455097079866bfca4d47"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" DROP CONSTRAINT "FK_e730d058a8c9ed3d18fc3b47c1b"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" DROP CONSTRAINT "FK_2d58976a00f8a93f42a0a2336a2"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" DROP CONSTRAINT "FK_6879a34afad6535e182a0a747b5"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_pick" DROP CONSTRAINT "FK_3c67219849b075794b044df64bf"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_selection" DROP CONSTRAINT "FK_dedab1017fb256df016a2bab002"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."draft_selection" DROP CONSTRAINT "FK_b70237128e7538a537c913cd706"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."permission" DROP CONSTRAINT "FK_c9d7f25e5a6cc7a117f2eb7f153"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."permission" DROP CONSTRAINT "FK_54b459f3ffe8a2420c1bb0aea5a"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_seat" DROP CONSTRAINT "FK_58ec0736cc3c2004c73747d8e34"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_seat" DROP CONSTRAINT "FK_4915e1817be2bc11b403d3f1e1a"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" DROP CONSTRAINT "FK_f62c50a4c0727ac36c7483ad7b2"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" DROP CONSTRAINT "FK_36d1cb7c0206190cdea231f9c39"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_position" DROP CONSTRAINT "FK_39b293f9c8e2bb2a5c26f7a6523"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_team" DROP CONSTRAINT "FK_9d86ca7e7759f11d2b6d4a9924d"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_staff_role" DROP CONSTRAINT "FK_8dceec978102c8fda542d208bd1"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_seat" DROP CONSTRAINT "FK_25e87db7d4b12006318f64fa302"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" DROP CONSTRAINT "FK_722a390774c594b1af95dc13b54"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" DROP CONSTRAINT "FK_aaa54ed884e4c3f6ec3187afcc6"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_appointment" DROP CONSTRAINT "FK_3ce0477eaed1b25d7031b5ac980"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP CONSTRAINT "FK_8122e5920a29af5ef76e2e2ff62"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP CONSTRAINT "FK_b9bb63f508aa958461750fb21db"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_profile" DROP CONSTRAINT "FK_65fe3ee2b2ebf66ddb515a4e5d1"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_profile" DROP CONSTRAINT "FK_afac34d97905cc53ae5e1b91b1d"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."photo" DROP CONSTRAINT "FK_3356374afaba354ff1838e0682b"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."approval" DROP CONSTRAINT "FK_22f5123d3c19de9eaf7f3998a5b"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" DROP CONSTRAINT "FK_2da59aebf7ccfc171d65aad6093"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" DROP CONSTRAINT "FK_6b96821a50975de3b039b64b7eb"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" DROP CONSTRAINT "FK_cb36315fa8d2eb02702153b579a"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_usage" DROP CONSTRAINT "FK_9fecdc70cde169c58d50bd60a98"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_skill_group" DROP CONSTRAINT "FK_30dc9ad00173ae281344068f932"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_skill_group" DROP CONSTRAINT "FK_adb40c3fbfade82e3293f62dd31"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role_use_limits" DROP CONSTRAINT "FK_4463e23dc3f6abce154bf3596f0"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player" DROP CONSTRAINT "FK_622bd2e2975785c536a74754290"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."player" DROP CONSTRAINT "FK_40e1ded9fbf4f2d9a6fcb9616a3"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_slot" DROP CONSTRAINT "FK_fa375ed496bbf66579f161992fa"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_slot" DROP CONSTRAINT "FK_5dc0fe96b415c76b42bf86c24d4"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team" DROP CONSTRAINT "FK_0cbb30ed058102b0f260e911e3c"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."team" DROP CONSTRAINT "FK_652e04e862dac0c611e6a929ab3"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" DROP CONSTRAINT "FK_7749e8dcc3f306fd33e9454fc36"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" DROP CONSTRAINT "FK_4d98bca47aa0b1d3f39e0b54d16"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."roster_role" DROP CONSTRAINT "FK_f0895013e2d4e16ca402f8aea7e"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" DROP CONSTRAINT "FK_c826d7607c5ca571346a6b52af1"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" DROP CONSTRAINT "FK_c42330f89150285a50e2f262e49"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_appointment" DROP CONSTRAINT "FK_ca08f0936b3922b98f999cee51f"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_seat" DROP CONSTRAINT "FK_a727550401c780f3d354601f1a4"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_role" DROP CONSTRAINT "FK_fb3577db7eaf1d3698f9bab3337"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_staff_role" DROP CONSTRAINT "FK_075a700938ebdcaef94e5672d57"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" DROP CONSTRAINT "FK_b73ec09ebdaf90554462be9b3da"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" DROP CONSTRAINT "FK_2c386e796af4d426f9c10678801"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group_assignment" DROP CONSTRAINT "FK_20184f6e40943fcbff3f2a1032e"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" DROP CONSTRAINT "FK_1b6a651f78ce0209633237fe945"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" DROP CONSTRAINT "FK_adb75cdee1e4c1c8740aeab36ca"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_group" DROP CONSTRAINT "FK_c5a9c04afe2cea55b9523321cbb"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_platform_account" DROP CONSTRAINT "FK_f7455aa82715ab0e817f8e6ade3"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member_platform_account" DROP CONSTRAINT "FK_f790210c8106972edb55c49f572"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_feature" DROP CONSTRAINT "FK_78074e38ced12d7aced41ebd67c"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_feature" DROP CONSTRAINT "FK_ac6faff211b59159157e52efeae"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."enabled_feature" DROP CONSTRAINT "FK_64c0a133010141ea04efdf3f9b7"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."enabled_feature" DROP CONSTRAINT "FK_c8a0693a644e1fd962f90e0654e"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization" DROP CONSTRAINT "FK_0b10df9cf789464c09784b32e4c"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."pronouns" DROP CONSTRAINT "FK_ab64820e64338ba71059368d8ba"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_mottos" DROP CONSTRAINT "FK_ce5e00022caab1c1e19dd7e040e"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group_type" DROP CONSTRAINT "FK_fb786f931ab2a1db8b6f8785940"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" DROP CONSTRAINT "FK_d1884396b8fe01bfef7c6166404"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" DROP CONSTRAINT "FK_ff8b23c2e61c484aec8bc1e3c6d"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_group" DROP CONSTRAINT "FK_6b2836d4ed4dff841b40d9bc1ee"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" DROP CONSTRAINT "FK_61ef1b6aff93c92ca17d2c64e1d"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" DROP CONSTRAINT "FK_78a0874f503f718434346afedc4"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."schedule_fixture" DROP CONSTRAINT "FK_e7a8e560ca504d498a245185afd"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."match_parent" DROP CONSTRAINT "FK_853b1e768cb493c250e7c7a23f1"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" DROP CONSTRAINT "FK_3c854126efbbf608a2682cffdea"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" DROP CONSTRAINT "FK_8c86d4dba2f71f4c6a235fb28a7"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scheduled_event" DROP CONSTRAINT "FK_0989bdf13136d091c2630a7f51b"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."game_mode" DROP CONSTRAINT "FK_1591079e6dddb2d90e90e94fdc2"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."scrim_meta" DROP CONSTRAINT "FK_0f9e7c4013624a6c635dd9c8558"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_cdacd386dc74af4e9cb12213049"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."round" DROP CONSTRAINT "FK_70694bc051fc00d714b6dfc07bd"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."round" DROP CONSTRAINT "FK_7f3ebe2c9b6582d68973dd1de22"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."verbiage" DROP CONSTRAINT "FK_8e06145c03deef3a10b5a0848fd"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."verbiage" DROP CONSTRAINT "FK_239465739873e831f435615d96d"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_value" DROP CONSTRAINT "FK_4583a3c108de67e025d108a63fb"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_value" DROP CONSTRAINT "FK_67dce788f993dd716050261f7a9"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."organization_configuration_allowed_value" DROP CONSTRAINT "FK_cb2355f94f406359ecee9637ddd"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."franchise_leadership_role" DROP CONSTRAINT "FK_7e2b3f74d7fd48a30ef15aec1de"`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "peak_mmr" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "salary" SET DEFAULT '-1'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "peak_mmr" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "salary" SET DEFAULT '-1'`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ALTER COLUMN "overtime_seconds" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ALTER COLUMN "chain" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."season" ALTER COLUMN "week_length" SET DEFAULT '7'`);
        await queryRunner.query(`DROP INDEX "sprocket"."IDX_b36a6dc7f05e2250f6789655ff"`);
        await queryRunner.query(`DROP INDEX "sprocket"."IDX_c5a64b96aa786ca91da4a91715"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game_platform"`);
        await queryRunner.query(`DROP INDEX "sprocket"."IDX_156686114faf2216039503a310"`);
        await queryRunner.query(`DROP INDEX "sprocket"."IDX_cb3d3008100cb2e46bcc932930"`);
        await queryRunner.query(`DROP TABLE "sprocket"."feature_dependency"`);
        await queryRunner.query(`DROP TABLE "sprocket"."player_stat_line"`);
        await queryRunner.query(`DROP TABLE "sprocket"."team_stat_line"`);
        await queryRunner.query(`DROP TABLE "sprocket"."eligibility_data"`);
        await queryRunner.query(`DROP TABLE "sprocket"."user_authentication_account"`);
        await queryRunner.query(`DROP TYPE "sprocket"."user_authentication_account_accounttype_enum"`);
        await queryRunner.query(`DROP TABLE "sprocket"."user"`);
        await queryRunner.query(`DROP TYPE "sprocket"."user_type_enum"`);
        await queryRunner.query(`DROP TABLE "sprocket"."user_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."user_roles"`);
        await queryRunner.query(`DROP TYPE "sprocket"."user_roles_accounttype_enum"`);
        await queryRunner.query(`DROP TABLE "sprocket"."draft_pick"`);
        await queryRunner.query(`DROP TABLE "sprocket"."draft_selection"`);
        await queryRunner.query(`DROP TABLE "sprocket"."sprocket_configuration"`);
        await queryRunner.query(`DROP TABLE "sprocket"."permission"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_staff_seat"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_staff_position"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_staff_team"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_staff_role"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_leadership_seat"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_leadership_appointment"`);
        await queryRunner.query(`DROP TABLE "sprocket"."member"`);
        await queryRunner.query(`DROP TABLE "sprocket"."member_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."photo"`);
        await queryRunner.query(`DROP TABLE "sprocket"."approval"`);
        await queryRunner.query(`DROP TABLE "sprocket"."roster_role_usage"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game_skill_group"`);
        await queryRunner.query(`DROP TABLE "sprocket"."roster_role_use_limits"`);
        await queryRunner.query(`DROP TABLE "sprocket"."player"`);
        await queryRunner.query(`DROP TABLE "sprocket"."roster_slot"`);
        await queryRunner.query(`DROP TABLE "sprocket"."team"`);
        await queryRunner.query(`DROP TABLE "sprocket"."roster_role"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game_skill_group_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_staff_appointment"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_staff_seat"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_staff_role"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_group_assignment"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_group"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_group_type"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_group_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game"`);
        await queryRunner.query(`DROP TABLE "sprocket"."platform"`);
        await queryRunner.query(`DROP TABLE "sprocket"."member_platform_account"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game_feature"`);
        await queryRunner.query(`DROP TABLE "sprocket"."feature"`);
        await queryRunner.query(`DROP TABLE "sprocket"."enabled_feature"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization"`);
        await queryRunner.query(`DROP TABLE "sprocket"."pronouns"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_profile"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_mottos"`);
        await queryRunner.query(`DROP TABLE "sprocket"."schedule_group_type"`);
        await queryRunner.query(`DROP TABLE "sprocket"."schedule_group"`);
        await queryRunner.query(`DROP TABLE "sprocket"."schedule_fixture"`);
        await queryRunner.query(`DROP TABLE "sprocket"."match_parent"`);
        await queryRunner.query(`DROP TABLE "sprocket"."scheduled_event"`);
        await queryRunner.query(`DROP TABLE "sprocket"."game_mode"`);
        await queryRunner.query(`DROP TABLE "sprocket"."scrim_meta"`);
        await queryRunner.query(`DROP TABLE "sprocket"."match"`);
        await queryRunner.query(`DROP TABLE "sprocket"."round"`);
        await queryRunner.query(`DROP TABLE "sprocket"."invalidation"`);
        await queryRunner.query(`DROP TABLE "sprocket"."verbiage"`);
        await queryRunner.query(`DROP TABLE "sprocket"."verbiage_code"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_configuration_value"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_configuration_key"`);
        await queryRunner.query(`DROP TABLE "sprocket"."organization_configuration_allowed_value"`);
        await queryRunner.query(`DROP TABLE "sprocket"."franchise_leadership_role"`);
        await queryRunner.query(`DROP TABLE "sprocket"."permission_bearer"`);
        await queryRunner.query(`DROP TABLE "sprocket"."action"`);
    }

}
