import {MigrationInterface, QueryRunner} from "typeorm";

export class Automigration1651451746292 implements MigrationInterface {
    name = 'Automigration1651451746292'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "public"."channel_map" ("channel_type" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "channel_id" character varying(255) NOT NULL, CONSTRAINT "PK_7db1c03d82e25e7bb2d1bd7fb36" PRIMARY KEY ("channel_type"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "channel_map_pkey" ON "public"."channel_map" ("channel_type") `);
        await queryRunner.query(`CREATE TABLE "public"."config" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "key" character varying(255) NOT NULL, "value" character varying(255) NOT NULL, CONSTRAINT "UQ_26489c99ddbb4c91631ef5cc791" UNIQUE ("key"), CONSTRAINT "PK_d0ee79a681413d50b0a4f98cf7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "config_key_unique" ON "public"."config" ("key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "config_pkey" ON "public"."config" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."team_branding" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "team_name" character varying(255) NOT NULL, "primary_color" character varying(255) NOT NULL, "secondary_color" character varying(255) NOT NULL, "logo_img_link" character varying(255) NOT NULL, "discord_emoji_id" character varying(255), CONSTRAINT "UQ_c0cda809595bf50e9363996f3c4" UNIQUE ("team_name"), CONSTRAINT "PK_f457f90bc6a8dc8cdc441c06f40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_branding_team_name_unique" ON "public"."team_branding" ("team_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_branding_pkey" ON "public"."team_branding" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."draft_order" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "season_season_number" integer NOT NULL, "original_team_name" character varying(255) NOT NULL, "team_name" character varying(255) NOT NULL, "league" text NOT NULL, "round" integer NOT NULL, "pick" integer NOT NULL, CONSTRAINT "UQ_52f68d99f225e1938ab35ffa7e5" UNIQUE ("season_season_number"), CONSTRAINT "UQ_bc3942df933649402075ae1a354" UNIQUE ("league"), CONSTRAINT "UQ_55008553ad87701e2c85417b3bf" UNIQUE ("round"), CONSTRAINT "UQ_5e37e1fe1e49c070aa0f5aa988d" UNIQUE ("pick"), CONSTRAINT "PK_f478946c183d98f8d88a94cfcd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "draft_order_season_season_number_league_round_pick_unique" ON "public"."draft_order" ("league", "pick", "round", "season_season_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "draft_order_pkey" ON "public"."draft_order" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."season" ("season_number" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "roster_locked" boolean NOT NULL DEFAULT false, "week_length" integer NOT NULL DEFAULT 7, CONSTRAINT "PK_fdca3fee69fdbeddbade5d100c7" PRIMARY KEY ("season_number"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "season_pkey" ON "public"."season" ("season_number") `);
        await queryRunner.query(`CREATE TABLE "public"."match" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "from" TIMESTAMP WITH TIME ZONE NOT NULL, "to" TIMESTAMP WITH TIME ZONE NOT NULL, "is_double_header" boolean NOT NULL, "season" integer NOT NULL, "match_number" integer NOT NULL, "map" character varying(255) NOT NULL DEFAULT 'CHAMPIONS_FIELD', CONSTRAINT "UQ_c09948fa55e9f3fbb43189b80a0" UNIQUE ("season"), CONSTRAINT "UQ_474c4ea820eafb556bc89dc4b48" UNIQUE ("match_number"), CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "match_season_match_number_unique" ON "public"."match" ("match_number", "season") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "match_pkey" ON "public"."match" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."fixture" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "home_name" character varying(255) NOT NULL, "away_name" character varying(255) NOT NULL, "match_id" integer NOT NULL, "channel_id" character varying(255) NOT NULL DEFAULT '', CONSTRAINT "UQ_aa46e5704233c54f18cc77134ab" UNIQUE ("home_name"), CONSTRAINT "UQ_37b0cf93e0f8f740c27d68c2f6b" UNIQUE ("away_name"), CONSTRAINT "UQ_9dd1fc0ee74c5dbc362bb9d082d" UNIQUE ("match_id"), CONSTRAINT "PK_d9634ba06480dc240af97ad548c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "fixture_pkey" ON "public"."fixture" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "fixture_home_name_away_name_match_id_unique" ON "public"."fixture" ("away_name", "home_name", "match_id") `);
        await queryRunner.query(`CREATE TABLE "public"."elo_data" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "player_id" integer NOT NULL, "replay_id" integer, "elo" real NOT NULL, "previous_node_id" integer, "next_node_id" integer, "chain" integer NOT NULL DEFAULT 0, "league" character varying(255), CONSTRAINT "UQ_283d060f9d008d02b17a936d1a3" UNIQUE ("player_id"), CONSTRAINT "UQ_dbd58feca9a6592f1ff8560f054" UNIQUE ("replay_id"), CONSTRAINT "UQ_ef56514ec709db01208dbfa3ac1" UNIQUE ("previous_node_id"), CONSTRAINT "UQ_62da6766a3d8863c197e9757970" UNIQUE ("next_node_id"), CONSTRAINT "REL_62da6766a3d8863c197e975797" UNIQUE ("next_node_id"), CONSTRAINT "REL_ef56514ec709db01208dbfa3ac" UNIQUE ("previous_node_id"), CONSTRAINT "PK_1330be890e846cbe967ad7fc02f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_previous_node_id_unique" ON "public"."elo_data" ("previous_node_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_player_id_replay_id_unique" ON "public"."elo_data" ("player_id", "replay_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_next_node_id_unique" ON "public"."elo_data" ("next_node_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_pkey" ON "public"."elo_data" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player_stats_core" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "color" text NOT NULL, "score" integer NOT NULL, "shots" integer NOT NULL, "goals" integer NOT NULL, "saves" integer NOT NULL, "assists" integer NOT NULL, "mvp" boolean NOT NULL, "mvpr" real NOT NULL, "player_id" integer, "replay_id" integer, CONSTRAINT "PK_62c5aa15ee82b456c9bea7a8e94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_stats_core_pkey" ON "public"."player_stats_core" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player_stats" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "start_time" integer NOT NULL, "end_time" integer NOT NULL, "car_name" character varying(255) NOT NULL, "car_id" integer NOT NULL, "steering_sensitivity" integer NOT NULL, "player_platform" character varying(255) NOT NULL, "camera_fov" integer NOT NULL, "camera_height" integer NOT NULL, "camera_pitch" integer NOT NULL, "camera_distance" integer NOT NULL, "camera_stiffness" integer NOT NULL, "camera_swivel_speed" integer NOT NULL, "camera_transition_speed" integer NOT NULL, "core_stats_id" integer NOT NULL, "boost_per_minute" integer NOT NULL, "boost_collected_per_minute" integer NOT NULL, "boost_average" integer NOT NULL, "boost_collected" integer NOT NULL, "boost_stolen" integer NOT NULL, "boost_collected_big" integer NOT NULL, "boost_stolen_big" integer NOT NULL, "boost_collected_small" integer NOT NULL, "boost_stolen_small" integer NOT NULL, "boost_count_collected_big" integer NOT NULL, "boost_count_stolen_big" integer NOT NULL, "boost_count_collected_small" integer NOT NULL, "boost_count_stolen_small" integer NOT NULL, "boost_overfill" integer NOT NULL, "boost_overfill_stolen" integer NOT NULL, "boost_wasted" integer NOT NULL, "boost_time_empty" integer NOT NULL, "boost_percent_empty" integer NOT NULL, "boost_time_full" integer NOT NULL, "boost_percent_full" integer NOT NULL, "boost_time0to25" integer NOT NULL, "boost_time25to50" integer NOT NULL, "boost_time50to75" integer NOT NULL, "boost_time75to100" integer NOT NULL, "boost_percent0to25" integer NOT NULL, "boost_percent25to50" integer NOT NULL, "boost_percent50to75" integer NOT NULL, "boost_percent75to100" integer NOT NULL, "avg_distance_to_ball" integer NOT NULL, "avg_distance_to_ball_possession" integer NOT NULL, "avg_distance_to_ball_no_possession" integer NOT NULL, "avg_distance_to_mates" integer NOT NULL, "time_defensive_third" integer NOT NULL, "time_neutral_third" integer NOT NULL, "time_offensive_third" integer NOT NULL, "time_defensive_half" integer NOT NULL, "time_offensive_half" integer NOT NULL, "time_behind_ball" integer NOT NULL, "time_infront_ball" integer NOT NULL, "time_most_back" integer NOT NULL, "time_most_forward" integer NOT NULL, "goals_against_while_last_defender" integer NOT NULL, "time_closest_to_ball" integer NOT NULL, "time_farthest_from_ball" integer NOT NULL, "percent_defensive_third" integer NOT NULL, "percent_offensive_third" integer NOT NULL, "percent_neutral_third" integer NOT NULL, "percent_defensive_half" integer NOT NULL, "percent_offensive_half" integer NOT NULL, "percent_behind_ball" integer NOT NULL, "percent_infront_ball" integer NOT NULL, "percent_most_back" integer NOT NULL, "percent_most_forward" integer NOT NULL, "percent_closest_to_ball" integer NOT NULL, "percent_farthest_from_ball" integer NOT NULL, "demos_inflicted" integer NOT NULL, "demos_taken" integer NOT NULL, "avg_speed" integer NOT NULL, "total_distance" integer NOT NULL, "time_supersonic_speed" integer NOT NULL, "time_boost_speed" integer NOT NULL, "time_slow_speed" integer NOT NULL, "time_ground" integer NOT NULL, "time_low_air" integer NOT NULL, "time_high_air" integer NOT NULL, "time_powerslide" integer NOT NULL, "count_powerslide" integer NOT NULL, "avg_powerslide_duration" integer NOT NULL, "avg_speed_percentage" integer NOT NULL, "percent_slow_speed" integer NOT NULL, "percent_boost_speed" integer NOT NULL, "percent_supersonic_speed" integer NOT NULL, "percent_ground" integer NOT NULL, "percent_low_air" integer NOT NULL, "percent_high_air" integer NOT NULL, "player_id" integer, "replay_id" integer, CONSTRAINT "UQ_e6fe07d43ed68fbb64b93ce5037" UNIQUE ("core_stats_id"), CONSTRAINT "REL_e6fe07d43ed68fbb64b93ce503" UNIQUE ("core_stats_id"), CONSTRAINT "PK_22e2d8ec820a98efbfdbf84d925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_stats_pkey" ON "public"."player_stats" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_stats_core_stats_id_unique" ON "public"."player_stats" ("core_stats_id") `);
        await queryRunner.query(`CREATE TABLE "public"."team_core_stats" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "team_name" character varying(255), "color" character varying(255), "goals" integer, "goals_against" integer, "possession_time" integer, "time_in_side" integer, "replay_id" integer, CONSTRAINT "PK_4607af5f62fe79cfc00c65d0223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_core_stats_pkey" ON "public"."team_core_stats" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."series_replay" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "map" character varying(255), "match_guid" character varying(255), "ballchasing_id" character varying(255), "duration" integer NOT NULL, "ncp" boolean NOT NULL DEFAULT false, "overtime" boolean NOT NULL, "overtime_seconds" integer NOT NULL DEFAULT 0, "winning_team_name" character varying(255), "winning_color" text, "played" TIMESTAMP WITH TIME ZONE, "is_dummy" boolean NOT NULL DEFAULT false, "series_id" integer, CONSTRAINT "UQ_bfa2984b8bdd5f98dae64423d37" UNIQUE ("match_guid"), CONSTRAINT "UQ_b31c4de7eadec55babfefc69ed0" UNIQUE ("duration"), CONSTRAINT "PK_5a3d50242f29f83b6dcb58cfe23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_replay_pkey" ON "public"."series_replay" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_replay_match_guid_unique" ON "public"."series_replay" ("duration", "match_guid") `);
        await queryRunner.query(`CREATE TABLE "public"."stream_event" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "channel" character varying(255) NOT NULL, "series_id" integer, "event_time" TIMESTAMP WITH TIME ZONE NOT NULL, "description" character varying(255) NOT NULL, "format" character varying(255) NOT NULL, "discord_id" character varying(255), CONSTRAINT "UQ_4660c96b60aecda7281b53f14a6" UNIQUE ("series_id"), CONSTRAINT "REL_4660c96b60aecda7281b53f14a" UNIQUE ("series_id"), CONSTRAINT "PK_f2c9f329f861e1ef0d30a16c000" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "stream_event_series_id_unique" ON "public"."stream_event" ("series_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "stream_event_pkey" ON "public"."stream_event" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."team_role_usage" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "team_name" character varying(255) NOT NULL, "league" text NOT NULL, "role" text NOT NULL, "series_id" integer, CONSTRAINT "PK_6e8aef458c3f239bc99871b31c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_role_usage_pkey" ON "public"."team_role_usage" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."series" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "league" character varying(255) NOT NULL DEFAULT 'UNKNOWN', "submission_timestamp" TIMESTAMP WITH TIME ZONE, "scheduled_time" TIMESTAMP WITH TIME ZONE, "full_ncp" boolean NOT NULL DEFAULT false, "mode" text NOT NULL, "fixture_id" integer, "scrim_id" integer, "stream_event_message_id" character varying(255), CONSTRAINT "UQ_baca13734353fed4536e63968bf" UNIQUE ("league"), CONSTRAINT "UQ_371dd8db459a94526009ee4d830" UNIQUE ("mode"), CONSTRAINT "UQ_2818d2ef39569bcc3b7f1249f4f" UNIQUE ("fixture_id"), CONSTRAINT "UQ_9e481f1024cf61c7d8d91d91ec9" UNIQUE ("scrim_id"), CONSTRAINT "REL_9e481f1024cf61c7d8d91d91ec" UNIQUE ("scrim_id"), CONSTRAINT "PK_e725676647382eb54540d7128ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_scrim_id_unique" ON "public"."series" ("scrim_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_pkey" ON "public"."series" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_league_fixture_id_mode_unique" ON "public"."series" ("fixture_id", "league", "mode") `);
        await queryRunner.query(`CREATE TABLE "public"."scrim" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "mode" text NOT NULL, "type" text NOT NULL, "base_scrim_points" integer NOT NULL, "author_id" integer, "host_id" integer, CONSTRAINT "PK_ddbb27697697aebc46418c38631" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "scrim_pkey" ON "public"."scrim" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."eligibility_data" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "player_id" integer NOT NULL, "scrim_id" integer NOT NULL, "scrim_points" integer NOT NULL, CONSTRAINT "PK_7adcd47caa5fc407a9ffd258c2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "eligibility_data_player_id_scrim_id" ON "public"."eligibility_data" ("player_id", "scrim_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "eligibility_data_pkey" ON "public"."eligibility_data" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."psyonix_api_result" ("id" SERIAL NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "playlist" integer NOT NULL, "tier" integer NOT NULL, "division" integer NOT NULL, "skill" integer NOT NULL, "matches_played" integer NOT NULL, "win_streak" integer NOT NULL, "sigma" integer NOT NULL, "mu" integer NOT NULL, "player_account_id" integer, CONSTRAINT "PK_065e28f9e5783d72034db5696fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "psyonix_api_result_pkey" ON "public"."psyonix_api_result" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player_account" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "platform" character varying(255) NOT NULL, "tracker" character varying(255), "platform_id" text DEFAULT '', "player_id" integer, CONSTRAINT "UQ_305bd4ad5417289051b326e85d8" UNIQUE ("platform"), CONSTRAINT "UQ_fb5d57725a7a7dd67308f6283a1" UNIQUE ("tracker"), CONSTRAINT "UQ_9d4152a98dffe1ed88d81befde8" UNIQUE ("platform_id"), CONSTRAINT "PK_8f34fdab2e0645520a937c67a70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_account_tracker_unique" ON "public"."player_account" ("tracker") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_account_platform_id_platform_unique" ON "public"."player_account" ("platform", "platform_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_account_pkey" ON "public"."player_account" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player_to_org" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "org_team" integer NOT NULL, "player_id" integer, CONSTRAINT "PK_1e65fa03c74c65552f2f99a1a5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_to_org_pkey" ON "public"."player_to_org" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."team_to_captain" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "player_id" integer NOT NULL, "team_name" character varying(255) NOT NULL, "league" character varying(255) NOT NULL DEFAULT 'UNKNOWN', CONSTRAINT "UQ_b57f2f97f58613a9bc1faf0fc45" UNIQUE ("player_id"), CONSTRAINT "UQ_fed6b7cac1ddc8653523bf9b6fa" UNIQUE ("team_name"), CONSTRAINT "UQ_bd362a6726194d0dc9faf2712f8" UNIQUE ("league"), CONSTRAINT "REL_b57f2f97f58613a9bc1faf0fc4" UNIQUE ("player_id"), CONSTRAINT "PK_a30cda54ddc6da8b45f79acadcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_to_captain_player_id_unique" ON "public"."team_to_captain" ("player_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_to_captain_team_name_league_unique" ON "public"."team_to_captain" ("league", "team_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_to_captain_pkey" ON "public"."team_to_captain" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "mleid" integer NOT NULL, "name" character varying(255) NOT NULL, "salary" real NOT NULL DEFAULT '-1.0', "team_name" character varying(255) NOT NULL DEFAULT 'FA', "league" character varying(255) NOT NULL DEFAULT 'UNKNOWN', "role" character varying(255), "preferred_platform" character varying(255), "peak_mmr" integer DEFAULT 0, "timezone" character varying(255) NOT NULL DEFAULT 'UNKNOWN', "discord_id" character varying(255), "mode_preference" text NOT NULL DEFAULT 'BOTH', "suspended" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_7baa5220210c74f8db27c06f8b4" UNIQUE ("name"), CONSTRAINT "PK_65edadc946a7faf4b638d5e8885" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_name_unique" ON "public"."player" ("name") `);
        await queryRunner.query(`CREATE INDEX "player_mleid_index" ON "public"."player" ("mleid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_pkey" ON "public"."player" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."team" ("name" character varying(255) NOT NULL, "created_by" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL, "updated_by" character varying(255) NOT NULL, "updated_at" TIMESTAMP NOT NULL, "franchise_manager_id" integer, "general_manager_id" integer, "doubles_assistant_general_manager_id" integer, "standard_assistant_general_manager_id" integer, "pr_support_id" integer, "callsign" character varying(255) NOT NULL, "branding_id" integer, "division_name" character varying(255), CONSTRAINT "UQ_88bb47771162c764eb6cf204ded" UNIQUE ("franchise_manager_id"), CONSTRAINT "UQ_196e7058905b52e64dada337502" UNIQUE ("general_manager_id"), CONSTRAINT "UQ_56f2d16783aeb1e7ab420c3c710" UNIQUE ("doubles_assistant_general_manager_id"), CONSTRAINT "UQ_7542836d5650bd551f1979acdca" UNIQUE ("standard_assistant_general_manager_id"), CONSTRAINT "UQ_a34208441605d74edd26d5932ab" UNIQUE ("pr_support_id"), CONSTRAINT "UQ_f457f90bc6a8dc8cdc441c06f40" UNIQUE ("branding_id"), CONSTRAINT "REL_f457f90bc6a8dc8cdc441c06f4" UNIQUE ("branding_id"), CONSTRAINT "REL_56f2d16783aeb1e7ab420c3c71" UNIQUE ("doubles_assistant_general_manager_id"), CONSTRAINT "REL_88bb47771162c764eb6cf204de" UNIQUE ("franchise_manager_id"), CONSTRAINT "REL_196e7058905b52e64dada33750" UNIQUE ("general_manager_id"), CONSTRAINT "REL_a34208441605d74edd26d5932a" UNIQUE ("pr_support_id"), CONSTRAINT "REL_7542836d5650bd551f1979acdc" UNIQUE ("standard_assistant_general_manager_id"), CONSTRAINT "PK_cf461f5b40cf1a2b8876011e1e1" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_standard_assistant_general_manager_id_unique" ON "public"."team" ("standard_assistant_general_manager_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_pr_support_id_unique" ON "public"."team" ("pr_support_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_pkey" ON "public"."team" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_general_manager_id_unique" ON "public"."team" ("general_manager_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_franchise_manager_id_unique" ON "public"."team" ("franchise_manager_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_doubles_assistant_general_manager_id_unique" ON "public"."team" ("doubles_assistant_general_manager_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_branding_id_unique" ON "public"."team" ("branding_id") `);
        await queryRunner.query(`CREATE TABLE "public"."division" ("name" character varying(255) NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "conference" text NOT NULL, CONSTRAINT "PK_296566b07c0653123c292aa2f85" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "division_pkey" ON "public"."division" ("name") `);
        await queryRunner.query(`CREATE TABLE "public"."footers" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "text" character varying(255) NOT NULL, CONSTRAINT "PK_303ae395bd278e349e12e6fb86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "footers_pkey" ON "public"."footers" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."league_branding" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "league" character varying(255) NOT NULL, "color" character varying(255) NOT NULL, "badge_img_link" character varying(255) NOT NULL, "discord_emoji_id" character varying(255), CONSTRAINT "UQ_dae88935437529861170e71e2e1" UNIQUE ("league"), CONSTRAINT "PK_a51404c7bca8f189c822cd31617" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "league_branding_league_unique" ON "public"."league_branding" ("league") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "league_branding_pkey" ON "public"."league_branding" ("id") `);
        await queryRunner.query(`CREATE TABLE "public"."player_history" ("history_id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "mleid" integer NOT NULL, "name" character varying(255) NOT NULL, "salary" real NOT NULL DEFAULT '-1.0', "team_name" character varying(255) NOT NULL DEFAULT 'FA', "league" character varying(255) NOT NULL DEFAULT 'UNKNOWN', "role" character varying(255), "preferred_platform" character varying(255), "peak_mmr" integer DEFAULT 0, "timezone" character varying(255) NOT NULL DEFAULT 'UNKNOWN', "discord_id" character varying(255), "mode_preference" text NOT NULL DEFAULT 'BOTH', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "suspended" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_90e001965a7f0806ce4be3fe816" PRIMARY KEY ("history_id"))`);
        await queryRunner.query(`CREATE INDEX "player_history_mleid_index" ON "public"."player_history" ("mleid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_history_pkey" ON "public"."player_history" ("history_id") `);
        await queryRunner.query(`CREATE TABLE "public"."salary_cap" ("id" SERIAL NOT NULL, "created_by" character varying(255) NOT NULL DEFAULT 'Unknown', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying(255) NOT NULL DEFAULT 'Unknown', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "league" character varying(255) NOT NULL, "max_salary" real NOT NULL, CONSTRAINT "UQ_8b69b4491606ba76999acd86e96" UNIQUE ("league"), CONSTRAINT "PK_766b18d6a4637b141c09cf85f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "salary_cap_league_unique" ON "public"."salary_cap" ("league") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "salary_cap_pkey" ON "public"."salary_cap" ("id") `);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" ADD CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5" FOREIGN KEY ("season_season_number") REFERENCES "public"."season"("season_number") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."match" ADD CONSTRAINT "FK_c09948fa55e9f3fbb43189b80a0" FOREIGN KEY ("season") REFERENCES "public"."season"("season_number") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."fixture" ADD CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d" FOREIGN KEY ("match_id") REFERENCES "public"."match"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" ADD CONSTRAINT "FK_62da6766a3d8863c197e9757970" FOREIGN KEY ("next_node_id") REFERENCES "public"."elo_data"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" ADD CONSTRAINT "FK_283d060f9d008d02b17a936d1a3" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" ADD CONSTRAINT "FK_ef56514ec709db01208dbfa3ac1" FOREIGN KEY ("previous_node_id") REFERENCES "public"."elo_data"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" ADD CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054" FOREIGN KEY ("replay_id") REFERENCES "public"."series_replay"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats_core" ADD CONSTRAINT "FK_8267be704f2cb632a389f02ae2e" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats_core" ADD CONSTRAINT "FK_33bce5d0b7b2ccfb3060a3c3c7d" FOREIGN KEY ("replay_id") REFERENCES "public"."series_replay"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" ADD CONSTRAINT "FK_e6fe07d43ed68fbb64b93ce5037" FOREIGN KEY ("core_stats_id") REFERENCES "public"."player_stats_core"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" ADD CONSTRAINT "FK_93f34075933141f2cadabb03eaf" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" ADD CONSTRAINT "FK_ea2095d76725ab154c06a8d4e76" FOREIGN KEY ("replay_id") REFERENCES "public"."series_replay"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team_core_stats" ADD CONSTRAINT "FK_17003b1050fed5c5a30719b0a26" FOREIGN KEY ("replay_id") REFERENCES "public"."series_replay"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."series_replay" ADD CONSTRAINT "FK_2986e645ba5ed6a1c74e353359e" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."stream_event" ADD CONSTRAINT "FK_4660c96b60aecda7281b53f14a6" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team_role_usage" ADD CONSTRAINT "FK_35e7bd852d23704926370eadd75" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."series" ADD CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f" FOREIGN KEY ("fixture_id") REFERENCES "public"."fixture"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."series" ADD CONSTRAINT "FK_9e481f1024cf61c7d8d91d91ec9" FOREIGN KEY ("scrim_id") REFERENCES "public"."scrim"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."scrim" ADD CONSTRAINT "FK_49ea9c6856dff085a24625d2c65" FOREIGN KEY ("author_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."scrim" ADD CONSTRAINT "FK_7dbaf913312637003aacbb06a75" FOREIGN KEY ("host_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."eligibility_data" ADD CONSTRAINT "FK_b5f6e39d3a45997b03cce28eaf4" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."eligibility_data" ADD CONSTRAINT "FK_fafc24cdfd41a1dbda0eef052b4" FOREIGN KEY ("scrim_id") REFERENCES "public"."scrim"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."psyonix_api_result" ADD CONSTRAINT "FK_98d7c263cab01a4bc6d1613ecaf" FOREIGN KEY ("player_account_id") REFERENCES "public"."player_account"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_account" ADD CONSTRAINT "FK_ffc4a663e88998079b9869cc2d9" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."player_to_org" ADD CONSTRAINT "FK_a38e40bba68951c336793b5b4b7" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team_to_captain" ADD CONSTRAINT "FK_b57f2f97f58613a9bc1faf0fc45" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_f457f90bc6a8dc8cdc441c06f40" FOREIGN KEY ("branding_id") REFERENCES "public"."team_branding"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_3d198d9995ec55f8c79f18dad9b" FOREIGN KEY ("division_name") REFERENCES "public"."division"("name") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_56f2d16783aeb1e7ab420c3c710" FOREIGN KEY ("doubles_assistant_general_manager_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_88bb47771162c764eb6cf204ded" FOREIGN KEY ("franchise_manager_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_196e7058905b52e64dada337502" FOREIGN KEY ("general_manager_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_a34208441605d74edd26d5932ab" FOREIGN KEY ("pr_support_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "public"."team" ADD CONSTRAINT "FK_7542836d5650bd551f1979acdca" FOREIGN KEY ("standard_assistant_general_manager_id") REFERENCES "public"."player"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_7542836d5650bd551f1979acdca"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_a34208441605d74edd26d5932ab"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_196e7058905b52e64dada337502"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_88bb47771162c764eb6cf204ded"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_56f2d16783aeb1e7ab420c3c710"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_3d198d9995ec55f8c79f18dad9b"`);
        await queryRunner.query(`ALTER TABLE "public"."team" DROP CONSTRAINT "FK_f457f90bc6a8dc8cdc441c06f40"`);
        await queryRunner.query(`ALTER TABLE "public"."team_to_captain" DROP CONSTRAINT "FK_b57f2f97f58613a9bc1faf0fc45"`);
        await queryRunner.query(`ALTER TABLE "public"."player_to_org" DROP CONSTRAINT "FK_a38e40bba68951c336793b5b4b7"`);
        await queryRunner.query(`ALTER TABLE "public"."player_account" DROP CONSTRAINT "FK_ffc4a663e88998079b9869cc2d9"`);
        await queryRunner.query(`ALTER TABLE "public"."psyonix_api_result" DROP CONSTRAINT "FK_98d7c263cab01a4bc6d1613ecaf"`);
        await queryRunner.query(`ALTER TABLE "public"."eligibility_data" DROP CONSTRAINT "FK_fafc24cdfd41a1dbda0eef052b4"`);
        await queryRunner.query(`ALTER TABLE "public"."eligibility_data" DROP CONSTRAINT "FK_b5f6e39d3a45997b03cce28eaf4"`);
        await queryRunner.query(`ALTER TABLE "public"."scrim" DROP CONSTRAINT "FK_7dbaf913312637003aacbb06a75"`);
        await queryRunner.query(`ALTER TABLE "public"."scrim" DROP CONSTRAINT "FK_49ea9c6856dff085a24625d2c65"`);
        await queryRunner.query(`ALTER TABLE "public"."series" DROP CONSTRAINT "FK_9e481f1024cf61c7d8d91d91ec9"`);
        await queryRunner.query(`ALTER TABLE "public"."series" DROP CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f"`);
        await queryRunner.query(`ALTER TABLE "public"."team_role_usage" DROP CONSTRAINT "FK_35e7bd852d23704926370eadd75"`);
        await queryRunner.query(`ALTER TABLE "public"."stream_event" DROP CONSTRAINT "FK_4660c96b60aecda7281b53f14a6"`);
        await queryRunner.query(`ALTER TABLE "public"."series_replay" DROP CONSTRAINT "FK_2986e645ba5ed6a1c74e353359e"`);
        await queryRunner.query(`ALTER TABLE "public"."team_core_stats" DROP CONSTRAINT "FK_17003b1050fed5c5a30719b0a26"`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" DROP CONSTRAINT "FK_ea2095d76725ab154c06a8d4e76"`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" DROP CONSTRAINT "FK_93f34075933141f2cadabb03eaf"`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats" DROP CONSTRAINT "FK_e6fe07d43ed68fbb64b93ce5037"`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats_core" DROP CONSTRAINT "FK_33bce5d0b7b2ccfb3060a3c3c7d"`);
        await queryRunner.query(`ALTER TABLE "public"."player_stats_core" DROP CONSTRAINT "FK_8267be704f2cb632a389f02ae2e"`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" DROP CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054"`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" DROP CONSTRAINT "FK_ef56514ec709db01208dbfa3ac1"`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" DROP CONSTRAINT "FK_283d060f9d008d02b17a936d1a3"`);
        await queryRunner.query(`ALTER TABLE "public"."elo_data" DROP CONSTRAINT "FK_62da6766a3d8863c197e9757970"`);
        await queryRunner.query(`ALTER TABLE "public"."fixture" DROP CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d"`);
        await queryRunner.query(`ALTER TABLE "public"."match" DROP CONSTRAINT "FK_c09948fa55e9f3fbb43189b80a0"`);
        await queryRunner.query(`ALTER TABLE "public"."draft_order" DROP CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5"`);
        await queryRunner.query(`DROP INDEX "public"."salary_cap_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."salary_cap_league_unique"`);
        await queryRunner.query(`DROP TABLE "public"."salary_cap"`);
        await queryRunner.query(`DROP INDEX "public"."player_history_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."player_history_mleid_index"`);
        await queryRunner.query(`DROP TABLE "public"."player_history"`);
        await queryRunner.query(`DROP INDEX "public"."league_branding_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."league_branding_league_unique"`);
        await queryRunner.query(`DROP TABLE "public"."league_branding"`);
        await queryRunner.query(`DROP INDEX "public"."footers_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."footers"`);
        await queryRunner.query(`DROP INDEX "public"."division_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."division"`);
        await queryRunner.query(`DROP INDEX "public"."team_branding_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_doubles_assistant_general_manager_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_franchise_manager_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_general_manager_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."team_pr_support_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_standard_assistant_general_manager_id_unique"`);
        await queryRunner.query(`DROP TABLE "public"."team"`);
        await queryRunner.query(`DROP INDEX "public"."player_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."player_mleid_index"`);
        await queryRunner.query(`DROP INDEX "public"."player_name_unique"`);
        await queryRunner.query(`DROP TABLE "public"."player"`);
        await queryRunner.query(`DROP INDEX "public"."team_to_captain_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."team_to_captain_team_name_league_unique"`);
        await queryRunner.query(`DROP INDEX "public"."team_to_captain_player_id_unique"`);
        await queryRunner.query(`DROP TABLE "public"."team_to_captain"`);
        await queryRunner.query(`DROP INDEX "public"."player_to_org_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."player_to_org"`);
        await queryRunner.query(`DROP INDEX "public"."player_account_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."player_account_platform_id_platform_unique"`);
        await queryRunner.query(`DROP INDEX "public"."player_account_tracker_unique"`);
        await queryRunner.query(`DROP TABLE "public"."player_account"`);
        await queryRunner.query(`DROP INDEX "public"."psyonix_api_result_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."psyonix_api_result"`);
        await queryRunner.query(`DROP INDEX "public"."eligibility_data_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."eligibility_data_player_id_scrim_id"`);
        await queryRunner.query(`DROP TABLE "public"."eligibility_data"`);
        await queryRunner.query(`DROP INDEX "public"."scrim_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."scrim"`);
        await queryRunner.query(`DROP INDEX "public"."series_league_fixture_id_mode_unique"`);
        await queryRunner.query(`DROP INDEX "public"."series_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."series_scrim_id_unique"`);
        await queryRunner.query(`DROP TABLE "public"."series"`);
        await queryRunner.query(`DROP INDEX "public"."team_role_usage_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."team_role_usage"`);
        await queryRunner.query(`DROP INDEX "public"."stream_event_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."stream_event_series_id_unique"`);
        await queryRunner.query(`DROP TABLE "public"."stream_event"`);
        await queryRunner.query(`DROP INDEX "public"."series_replay_match_guid_unique"`);
        await queryRunner.query(`DROP INDEX "public"."series_replay_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."series_replay"`);
        await queryRunner.query(`DROP INDEX "public"."team_core_stats_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."team_core_stats"`);
        await queryRunner.query(`DROP INDEX "public"."player_stats_core_stats_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."player_stats_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."player_stats"`);
        await queryRunner.query(`DROP INDEX "public"."player_stats_core_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."player_stats_core"`);
        await queryRunner.query(`DROP INDEX "public"."elo_data_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."elo_data_next_node_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."elo_data_player_id_replay_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."elo_data_previous_node_id_unique"`);
        await queryRunner.query(`DROP TABLE "public"."elo_data"`);
        await queryRunner.query(`DROP INDEX "public"."fixture_home_name_away_name_match_id_unique"`);
        await queryRunner.query(`DROP INDEX "public"."fixture_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."fixture"`);
        await queryRunner.query(`DROP INDEX "public"."match_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."match_season_match_number_unique"`);
        await queryRunner.query(`DROP TABLE "public"."match"`);
        await queryRunner.query(`DROP INDEX "public"."season_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."season"`);
        await queryRunner.query(`DROP INDEX "public"."draft_order_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."draft_order_season_season_number_league_round_pick_unique"`);
        await queryRunner.query(`DROP TABLE "public"."draft_order"`);
        await queryRunner.query(`DROP INDEX "public"."team_branding_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."team_branding_team_name_unique"`);
        await queryRunner.query(`DROP TABLE "public"."team_branding"`);
        await queryRunner.query(`DROP INDEX "public"."config_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."config_key_unique"`);
        await queryRunner.query(`DROP TABLE "public"."config"`);
        await queryRunner.query(`DROP INDEX "public"."channel_map_pkey"`);
        await queryRunner.query(`DROP TABLE "public"."channel_map"`);
    }

}
