import {MigrationInterface, QueryRunner} from "typeorm";

export class Automigration1652212664701 implements MigrationInterface {
    name = 'Automigration1652212664701'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "UQ_4fd5ae50f2d3808233b3a73f6eb"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" RENAME COLUMN "discordId" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" RENAME CONSTRAINT "UQ_cb0df66149e4aab52ac820afbce" TO "UQ_08897b166dee565859b7fb2fcc8"`);
        await queryRunner.query(`CREATE TYPE "sprocket"."member_restriction_type_enum" AS ENUM('QUEUE_BAN')`);
        await queryRunner.query(`CREATE TABLE "sprocket"."member_restriction" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "sprocket"."member_restriction_type_enum" NOT NULL, "expiration" TIMESTAMP NOT NULL, "manualExpiration" TIMESTAMP, "memberId" integer NOT NULL, CONSTRAINT "PK_45e411646addd834fb79d1bf26c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`DROP INDEX "mledb"."player_account_platform_id_platform_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" ADD CONSTRAINT "UQ_305bd4ad5417289051b326e85d8" UNIQUE ("platform")`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" ADD CONSTRAINT "UQ_fb5d57725a7a7dd67308f6283a1" UNIQUE ("tracker")`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" ADD CONSTRAINT "UQ_9d4152a98dffe1ed88d81befde8" UNIQUE ("platform_id")`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "salary" SET DEFAULT '-1.0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "peak_mmr" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "FK_283d060f9d008d02b17a936d1a3"`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054"`);
        await queryRunner.query(`DROP INDEX "mledb"."elo_data_player_id_replay_id_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "UQ_283d060f9d008d02b17a936d1a3" UNIQUE ("player_id")`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "UQ_dbd58feca9a6592f1ff8560f054" UNIQUE ("replay_id")`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ALTER COLUMN "chain" SET DEFAULT 0`);
        await queryRunner.query(`DROP INDEX "mledb"."series_replay_match_guid_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ADD CONSTRAINT "UQ_bfa2984b8bdd5f98dae64423d37" UNIQUE ("match_guid")`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ADD CONSTRAINT "UQ_b31c4de7eadec55babfefc69ed0" UNIQUE ("duration")`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ALTER COLUMN "overtime_seconds" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" DROP CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f"`);
        await queryRunner.query(`DROP INDEX "mledb"."series_league_fixture_id_mode_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" ADD CONSTRAINT "UQ_baca13734353fed4536e63968bf" UNIQUE ("league")`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" ADD CONSTRAINT "UQ_371dd8db459a94526009ee4d830" UNIQUE ("mode")`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" ADD CONSTRAINT "UQ_2818d2ef39569bcc3b7f1249f4f" UNIQUE ("fixture_id")`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" DROP CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d"`);
        await queryRunner.query(`DROP INDEX "mledb"."fixture_home_name_away_name_match_id_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" ADD CONSTRAINT "UQ_aa46e5704233c54f18cc77134ab" UNIQUE ("home_name")`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" ADD CONSTRAINT "UQ_37b0cf93e0f8f740c27d68c2f6b" UNIQUE ("away_name")`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" ADD CONSTRAINT "UQ_9dd1fc0ee74c5dbc362bb9d082d" UNIQUE ("match_id")`);
        await queryRunner.query(`DROP INDEX "mledb"."match_season_match_number_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."match" ADD CONSTRAINT "UQ_474c4ea820eafb556bc89dc4b48" UNIQUE ("match_number")`);
        await queryRunner.query(`ALTER TABLE "mledb"."season" ALTER COLUMN "week_length" SET DEFAULT 7`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "UQ_52f68d99f225e1938ab35ffa7e5" UNIQUE ("season_season_number")`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "UQ_bc3942df933649402075ae1a354" UNIQUE ("league")`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "UQ_55008553ad87701e2c85417b3bf" UNIQUE ("round")`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "UQ_5e37e1fe1e49c070aa0f5aa988d" UNIQUE ("pick")`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "salary" SET DEFAULT '-1.0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "peak_mmr" SET DEFAULT 0`);
        await queryRunner.query(`DROP INDEX "mledb"."team_to_captain_team_name_league_unique"`);
        await queryRunner.query(`ALTER TABLE "mledb"."team_to_captain" ADD CONSTRAINT "UQ_fed6b7cac1ddc8653523bf9b6fa" UNIQUE ("team_name")`);
        await queryRunner.query(`ALTER TABLE "mledb"."team_to_captain" ADD CONSTRAINT "UQ_bd362a6726194d0dc9faf2712f8" UNIQUE ("league")`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP CONSTRAINT "UQ_08897b166dee565859b7fb2fcc8"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD "userId" integer`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_account_platform_id_platform_unique" ON "mledb"."player_account" ("platform", "platform_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_player_id_replay_id_unique" ON "mledb"."elo_data" ("player_id", "replay_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_replay_match_guid_unique" ON "mledb"."series_replay" ("duration", "match_guid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_league_fixture_id_mode_unique" ON "mledb"."series" ("fixture_id", "league", "mode") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "fixture_home_name_away_name_match_id_unique" ON "mledb"."fixture" ("away_name", "home_name", "match_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "match_season_match_number_unique" ON "mledb"."match" ("match_number", "season") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "draft_order_season_season_number_league_round_pick_unique" ON "mledb"."draft_order" ("league", "pick", "round", "season_season_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_to_captain_team_name_league_unique" ON "mledb"."team_to_captain" ("league", "team_name") `);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054" FOREIGN KEY ("replay_id") REFERENCES "mledb"."series_replay"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "FK_283d060f9d008d02b17a936d1a3" FOREIGN KEY ("player_id") REFERENCES "mledb"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" ADD CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f" FOREIGN KEY ("fixture_id") REFERENCES "mledb"."fixture"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" ADD CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d" FOREIGN KEY ("match_id") REFERENCES "mledb"."match"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5" FOREIGN KEY ("season_season_number") REFERENCES "mledb"."season"("season_number") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD CONSTRAINT "FK_08897b166dee565859b7fb2fcc8" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP CONSTRAINT "FK_08897b166dee565859b7fb2fcc8"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5"`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" DROP CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" DROP CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f"`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "FK_283d060f9d008d02b17a936d1a3"`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054"`);
        await queryRunner.query(`DROP INDEX "mledb"."team_to_captain_team_name_league_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."draft_order_season_season_number_league_round_pick_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."match_season_match_number_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."fixture_home_name_away_name_match_id_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."series_league_fixture_id_mode_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."series_replay_match_guid_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."elo_data_player_id_replay_id_unique"`);
        await queryRunner.query(`DROP INDEX "mledb"."player_account_platform_id_platform_unique"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" ADD CONSTRAINT "UQ_08897b166dee565859b7fb2fcc8" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "mledb"."team_to_captain" DROP CONSTRAINT "UQ_bd362a6726194d0dc9faf2712f8"`);
        await queryRunner.query(`ALTER TABLE "mledb"."team_to_captain" DROP CONSTRAINT "UQ_fed6b7cac1ddc8653523bf9b6fa"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "team_to_captain_team_name_league_unique" ON "mledb"."team_to_captain" ("team_name", "league") `);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "peak_mmr" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_history" ALTER COLUMN "salary" SET DEFAULT '-1'`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "UQ_5e37e1fe1e49c070aa0f5aa988d"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "UQ_55008553ad87701e2c85417b3bf"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "UQ_bc3942df933649402075ae1a354"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" DROP CONSTRAINT "UQ_52f68d99f225e1938ab35ffa7e5"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "FK_52f68d99f225e1938ab35ffa7e5" FOREIGN KEY ("season_season_number") REFERENCES "mledb"."season"("season_number") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."season" ALTER COLUMN "week_length" SET DEFAULT '7'`);
        await queryRunner.query(`ALTER TABLE "mledb"."match" DROP CONSTRAINT "UQ_474c4ea820eafb556bc89dc4b48"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "match_season_match_number_unique" ON "mledb"."match" ("match_number", "season") `);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" DROP CONSTRAINT "UQ_9dd1fc0ee74c5dbc362bb9d082d"`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" DROP CONSTRAINT "UQ_37b0cf93e0f8f740c27d68c2f6b"`);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" DROP CONSTRAINT "UQ_aa46e5704233c54f18cc77134ab"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "fixture_home_name_away_name_match_id_unique" ON "mledb"."fixture" ("home_name", "away_name", "match_id") `);
        await queryRunner.query(`ALTER TABLE "mledb"."fixture" ADD CONSTRAINT "FK_9dd1fc0ee74c5dbc362bb9d082d" FOREIGN KEY ("match_id") REFERENCES "mledb"."match"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" DROP CONSTRAINT "UQ_2818d2ef39569bcc3b7f1249f4f"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" DROP CONSTRAINT "UQ_371dd8db459a94526009ee4d830"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series" DROP CONSTRAINT "UQ_baca13734353fed4536e63968bf"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_league_fixture_id_mode_unique" ON "mledb"."series" ("league", "mode", "fixture_id") `);
        await queryRunner.query(`ALTER TABLE "mledb"."series" ADD CONSTRAINT "FK_2818d2ef39569bcc3b7f1249f4f" FOREIGN KEY ("fixture_id") REFERENCES "mledb"."fixture"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" ALTER COLUMN "overtime_seconds" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" DROP CONSTRAINT "UQ_b31c4de7eadec55babfefc69ed0"`);
        await queryRunner.query(`ALTER TABLE "mledb"."series_replay" DROP CONSTRAINT "UQ_bfa2984b8bdd5f98dae64423d37"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "series_replay_match_guid_unique" ON "mledb"."series_replay" ("match_guid", "duration") `);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ALTER COLUMN "chain" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "UQ_dbd58feca9a6592f1ff8560f054"`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" DROP CONSTRAINT "UQ_283d060f9d008d02b17a936d1a3"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "elo_data_player_id_replay_id_unique" ON "mledb"."elo_data" ("player_id", "replay_id") `);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "FK_dbd58feca9a6592f1ff8560f054" FOREIGN KEY ("replay_id") REFERENCES "mledb"."series_replay"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."elo_data" ADD CONSTRAINT "FK_283d060f9d008d02b17a936d1a3" FOREIGN KEY ("player_id") REFERENCES "mledb"."player"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "peak_mmr" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player" ALTER COLUMN "salary" SET DEFAULT '-1'`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" DROP CONSTRAINT "UQ_9d4152a98dffe1ed88d81befde8"`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" DROP CONSTRAINT "UQ_fb5d57725a7a7dd67308f6283a1"`);
        await queryRunner.query(`ALTER TABLE "mledb"."player_account" DROP CONSTRAINT "UQ_305bd4ad5417289051b326e85d8"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "player_account_platform_id_platform_unique" ON "mledb"."player_account" ("platform", "platform_id") `);
        await queryRunner.query(`DROP TABLE "sprocket"."member_restriction"`);
        await queryRunner.query(`DROP TYPE "sprocket"."member_restriction_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" RENAME CONSTRAINT "UQ_08897b166dee565859b7fb2fcc8" TO "UQ_cb0df66149e4aab52ac820afbce"`);
        await queryRunner.query(`ALTER TABLE "sprocket"."member" RENAME COLUMN "userId" TO "discordId"`);
        await queryRunner.query(`ALTER TABLE "mledb"."draft_order" ADD CONSTRAINT "UQ_4fd5ae50f2d3808233b3a73f6eb" UNIQUE ("season_season_number", "league", "round", "pick")`);
    }

}
