import { MigrationInterface, QueryRunner } from "typeorm";
export class untitledMigration1767035052316 implements MigrationInterface {
  name = 'untitledMigration1767035052316'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS sprocket AUTHORIZATION postgres`);
    await queryRunner.query(`CREATE TABLE "sprocket"."game_mode" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "playerCount" integer NOT NULL, "teamSize" integer NOT NULL, "gameId" uuid, CONSTRAINT "game-name-unq" UNIQUE ("gameId", "name"), CONSTRAINT "PK_ef9a2ad96f7bcea1655cd17e575" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."skill_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "code" character varying NOT NULL, "rank" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "gameId" uuid, CONSTRAINT "UQ_6fdf4027ecd26569aa7702ac1eb" UNIQUE ("name", "code", "gameId"), CONSTRAINT "PK_7aba2020a477493c6620acebb30" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."game" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "statDefinitions" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "UQ_5d1e08e04b97aa06d671cd58409" UNIQUE ("name"), CONSTRAINT "PK_352a30652cd352f552fef73dec5" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."franchise_role_roletype_enum" AS ENUM('manager', 'assistant_manager')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."franchise_role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "roleType" "sprocket"."franchise_role_roletype_enum" NOT NULL, "assignedAt" TIMESTAMP NOT NULL, "requiresApproval" boolean NOT NULL DEFAULT false, "franchiseId" uuid, "userId" uuid, "assignedById" uuid, CONSTRAINT "PK_1edbd77df939e2053c940ced539" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."franchise" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "logoUrl" character varying, "primaryColor" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_b209412e69a3f5fe77ec9d31e0b" UNIQUE ("name"), CONSTRAINT "UQ_de595b902faa36237a25abc097e" UNIQUE ("slug"), CONSTRAINT "PK_0d92e63ee108403e7f251ef8e35" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."club_role_roletype_enum" AS ENUM('general_manager', 'assistant_gm')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."club_role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "roleType" "sprocket"."club_role_roletype_enum" NOT NULL, "assignedAt" TIMESTAMP NOT NULL, "requiresApproval" boolean NOT NULL DEFAULT false, "clubId" uuid, "userId" uuid, "assignedById" uuid, CONSTRAINT "PK_9098940a2362b9b5996d6d9bce9" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."club" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "franchiseId" uuid, "gameId" uuid, CONSTRAINT "UQ_f8387c04fc077b826b2ad11825e" UNIQUE ("slug"), CONSTRAINT "PK_79282481e036a6e0b180afa38aa" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."team_role_roletype_enum" AS ENUM('captain', 'assistant_captain')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."team_role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "roleType" "sprocket"."team_role_roletype_enum" NOT NULL, "assignedAt" TIMESTAMP NOT NULL, "requiresApproval" boolean NOT NULL DEFAULT false, "teamId" uuid, "userId" uuid, "assignedById" uuid, CONSTRAINT "PK_b4d9c800f392007b4e5a19f90ef" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."team" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "rosterSizeLimit" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "clubId" uuid, "skillGroupId" uuid, CONSTRAINT "UQ_e459cfa57273996b76d24a0fa68" UNIQUE ("slug"), CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."season_status_enum" AS ENUM('upcoming', 'active', 'completed')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."season" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "number" integer NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "status" "sprocket"."season_status_enum" NOT NULL DEFAULT 'upcoming', "isOffseason" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8ac0d081dbdb7ab02d166bcda9f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."roster_spot_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."roster_spot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "status" "sprocket"."roster_spot_status_enum" NOT NULL, "joinedAt" TIMESTAMP NOT NULL, "leftAt" TIMESTAMP, "metadata" jsonb, "teamId" uuid, "playerId" uuid, "seasonId" uuid, CONSTRAINT "PK_0b5bb1d509eb73861b924c0435a" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."roster_offer_status_enum" AS ENUM('pending', 'accepted', 'declined', 'withdrawn')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."roster_offer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "status" "sprocket"."roster_offer_status_enum" NOT NULL, "offeredAt" TIMESTAMP NOT NULL, "respondedAt" TIMESTAMP, "message" text, "teamId" uuid, "playerId" uuid, "seasonId" uuid, "offeredById" uuid, CONSTRAINT "PK_b54bb2ba48f0e7c7591c1e75d35" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."player" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "salary" character varying NOT NULL, "userId" uuid, "gameId" uuid, "skillGroupId" uuid, CONSTRAINT "UQ_1226352721f49996c9bf0bbe9d2" UNIQUE ("gameId", "userId"), CONSTRAINT "PK_65edadc946a7faf4b638d5e8885" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."user_auth_account_platform_enum" AS ENUM('DISCORD', 'STEAM')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."user_auth_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "platform" "sprocket"."user_auth_account_platform_enum" NOT NULL, "platformId" character varying NOT NULL, "platformName" character varying NOT NULL, "avatarUrl" character varying, "userId" uuid NOT NULL, CONSTRAINT "unique_auth_account" UNIQUE ("platform", "platformId"), CONSTRAINT "PK_1162672db36e898248f0bd8da17" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "avatarUrl" character varying, "active" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."seat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL, "roleId" uuid, CONSTRAINT "UQ_72ceaf61b10994e1545fcea8cd3" UNIQUE ("name"), CONSTRAINT "PK_4e72ae40c3fbd7711ccb380ac17" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."player_stat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "stats" jsonb NOT NULL DEFAULT '{}', "playerId" uuid, "roundId" uuid, CONSTRAINT "PK_ed3543c123f2d2c52da0555599a" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."team_stat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "stats" jsonb NOT NULL DEFAULT '{}', "teamId" uuid, "roundId" uuid, CONSTRAINT "PK_02ca423da304123f0bbe8e63d88" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."round" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "roundNumber" integer NOT NULL, "isMapCheck" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}', "matchId" uuid, CONSTRAINT "PK_34bd959f3f4a90eb86e4ae24d2d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."match_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
    await queryRunner.query(`CREATE TYPE "sprocket"."match_state_enum" AS ENUM('PENDING', 'POPPED', 'IN_PROGRESS', 'RATIFYING', 'COMPLETE', 'LOCKED', 'CANCELLED')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."match" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "status" "sprocket"."match_status_enum" NOT NULL DEFAULT 'PENDING', "startTime" TIMESTAMP, "endTime" TIMESTAMP, "authorId" uuid, "organizationId" character varying, "settings" jsonb DEFAULT '{}', "state" "sprocket"."match_state_enum" DEFAULT 'PENDING', "maxPlayers" integer, "pendingExpiresAt" TIMESTAMP, "poppedExpiresAt" TIMESTAMP, "type" character varying NOT NULL, "gameId" uuid, "gameModeId" uuid, "homeFranchiseId" uuid, "awayFranchiseId" uuid, "skillGroupId" uuid, CONSTRAINT "PK_92b6c3a6631dd5b24a67c69f69d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_4c90e9976d9356c8d4ec5013ff" ON "sprocket"."match" ("type") `);
    await queryRunner.query(`CREATE TABLE "sprocket"."schedule_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9579e4a3a46e2afdae0b757048" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."schedule_group_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_33f1d34f327abe56f6b1a3f716a" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."club_seat_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "seatId" uuid, "userId" uuid, "clubId" uuid, CONSTRAINT "PK_4dc326170a1a9159d6cc74846f4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."franchise_seat_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "seatId" uuid, "userId" uuid, "franchiseId" uuid, CONSTRAINT "PK_064bd0f2b94c7f03a403a327965" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."team_seat_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "seatId" uuid, "userId" uuid, "teamId" uuid, CONSTRAINT "PK_06a2aec48f6bbb2f401ef5d05f4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."organization_seat_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "seatId" uuid, "userId" uuid, CONSTRAINT "PK_095ebd883942a1f40a2cda2973c" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "casbin_rule" ("id" SERIAL NOT NULL, "ptype" character varying, "v0" character varying, "v1" character varying, "v2" character varying, "v3" character varying, "v4" character varying, "v5" character varying, CONSTRAINT "PK_e147354d31e2748a3a5da5e3060" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "role_definition" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "displayName" character varying NOT NULL, "description" text, "hierarchy" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "isRestricted" boolean NOT NULL DEFAULT false, "metadata" jsonb, CONSTRAINT "UQ_673a363e51839240670650d1e21" UNIQUE ("name"), CONSTRAINT "PK_9661058a685d2ed1b0a4479458f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "public"."user_role_status_enum" AS ENUM('pending', 'active', 'rejected')`);
    await queryRunner.query(`CREATE TABLE "user_role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "scope" character varying, "assignedAt" TIMESTAMP NOT NULL, "assignedById" uuid, "expiresAt" TIMESTAMP, "requiresApproval" boolean NOT NULL DEFAULT false, "status" "public"."user_role_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "public"."permission_audit_log_action_enum" AS ENUM('grant_role', 'revoke_role', 'add_policy', 'remove_policy', 'approve_role', 'reject_role')`);
    await queryRunner.query(`CREATE TABLE "permission_audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" uuid, "action" "public"."permission_audit_log_action_enum" NOT NULL, "details" jsonb NOT NULL, "timestamp" TIMESTAMP NOT NULL, "reason" character varying, CONSTRAINT "PK_bf08d9b87a5276cb25b343f5533" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."notification_template_channel_enum" AS ENUM('EMAIL', 'PUSH', 'SMS', 'IN_APP', 'DISCORD', 'WEBHOOK')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."notification_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "channel" "sprocket"."notification_template_channel_enum" NOT NULL, "content" text NOT NULL, "defaultData" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_d2a6ef77141a01b8ac31f514cfc" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."notification_history_channel_enum" AS ENUM('EMAIL', 'PUSH', 'SMS', 'IN_APP', 'DISCORD', 'WEBHOOK')`);
    await queryRunner.query(`CREATE TYPE "sprocket"."notification_history_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'RETRYING')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."notification_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "channel" "sprocket"."notification_history_channel_enum" NOT NULL, "recipientId" character varying NOT NULL, "status" "sprocket"."notification_history_status_enum" NOT NULL DEFAULT 'PENDING', "templateName" character varying NOT NULL, "templateData" jsonb NOT NULL DEFAULT '{}', "errorMessage" character varying, "retryCount" integer NOT NULL DEFAULT '0', "sentAt" TIMESTAMP, "templateId" uuid, "userId" uuid, CONSTRAINT "PK_901f37d36fcc63dffdc1281d6bd" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."user_notification_preference_channel_enum" AS ENUM('EMAIL', 'PUSH', 'SMS', 'IN_APP', 'DISCORD', 'WEBHOOK')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."user_notification_preference" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "channel" "sprocket"."user_notification_preference_channel_enum" NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "settings" jsonb NOT NULL DEFAULT '{}', "userId" uuid, CONSTRAINT "user-channel-unq" UNIQUE ("userId", "channel"), CONSTRAINT "PK_98bedc3257235969f6ff2ec6682" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "level" character varying(10) NOT NULL, "message" text NOT NULL, "context" character varying(100), "service" character varying(100) NOT NULL, "method" character varying(50), "path" character varying(200), "statusCode" integer, "duration" integer, "error" text, "trace" text, "userId" uuid, "requestId" character varying(100), "traceId" character varying(100), "spanId" character varying(100), "tags" jsonb, CONSTRAINT "PK_fb1b805f2f7795de79fa69340ba" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "value" numeric(20,6) NOT NULL, "type" character varying(20) NOT NULL, "unit" character varying(20), "service" character varying(100) NOT NULL, "method" character varying(50), "path" character varying(200), "labels" jsonb, "userId" uuid, "requestId" character varying(100), "traceId" character varying(100), "spanId" character varying(100), CONSTRAINT "PK_5283cad666a83376e28a715bf0e" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."scrim_queue_status_enum" AS ENUM('QUEUED', 'MATCHED', 'EXPIRED', 'CANCELLED')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."scrim_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "skillRating" integer NOT NULL, "queuedAt" TIMESTAMP NOT NULL, "status" "sprocket"."scrim_queue_status_enum" NOT NULL, "matchedAt" TIMESTAMP, "playerId" uuid, "gameId" uuid, "matchId" uuid, CONSTRAINT "PK_fd5e09a30ba9a9427d6f04a6eb0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."scrim_timeout" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expiresAt" TIMESTAMP NOT NULL, "reason" character varying NOT NULL, "playerId" uuid, CONSTRAINT "PK_7a336c4d272131358531144464d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."match_submission_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', 'VALIDATING', 'RATIFYING', 'RATIFIED')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."match_submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "status" "sprocket"."match_submission_status_enum" NOT NULL, "submittedData" jsonb NOT NULL, "submittedAt" TIMESTAMP NOT NULL, "reviewedAt" TIMESTAMP, "rejectionReason" character varying, "matchId" uuid, "submittedById" uuid, "reviewedById" uuid, CONSTRAINT "PK_e27221709605a1307300f783216" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "public"."event_queue_eventtype_enum" AS ENUM('MATCH_COMPLETED', 'PLAYER_JOINED_QUEUE', 'SUBMISSION_CREATED', 'MATCH_RATIFIED')`);
    await queryRunner.query(`CREATE TYPE "public"."event_queue_status_enum" AS ENUM('PENDING', 'PROCESSED', 'FAILED')`);
    await queryRunner.query(`CREATE TYPE "public"."event_queue_targetservice_enum" AS ENUM('NOTIFICATIONS', 'IMAGE_GEN', 'REPLAY_PARSE', 'ELO_SERVICE')`);
    await queryRunner.query(`CREATE TABLE "event_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "eventType" "public"."event_queue_eventtype_enum" NOT NULL, "payload" jsonb NOT NULL, "processedAt" TIMESTAMP, "status" "public"."event_queue_status_enum" NOT NULL DEFAULT 'PENDING', "retryCount" integer NOT NULL DEFAULT '0', "targetService" "public"."event_queue_targetservice_enum" NOT NULL, CONSTRAINT "PK_f2ab43ee6a569a89ba286db2fa6" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."elo_rating_node_nodetype_enum" AS ENUM('initial', 'match_output', 'compacted')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."elo_rating_node" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "rating" double precision NOT NULL, "uncertainty" double precision, "isCompacted" boolean NOT NULL DEFAULT false, "nodeType" "sprocket"."elo_rating_node_nodetype_enum" NOT NULL, "type" character varying NOT NULL, "playerId" uuid, "gameId" uuid, "sourceMatchId" uuid, CONSTRAINT "PK_16cc6de6229ea45249b054d2e14" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_502a69634aabbb35348592bdc4" ON "sprocket"."elo_rating_node" ("type") `);
    await queryRunner.query(`CREATE TABLE "sprocket"."match_rating_calculation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "ratingChange" double precision NOT NULL, "isInvalidated" boolean NOT NULL DEFAULT false, "invalidatedAt" TIMESTAMP, "calculationMetadata" jsonb, "matchId" uuid, "playerId" uuid, "gameId" uuid, "inputRatingId" uuid, "outputRatingId" uuid, CONSTRAINT "PK_002b3098e9655cd637aad6ab36f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "sprocket"."game_rating_config_system_enum" AS ENUM('elo', 'glicko', 'trueskill')`);
    await queryRunner.query(`CREATE TABLE "sprocket"."game_rating_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "system" "sprocket"."game_rating_config_system_enum" NOT NULL, "parameters" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "effectiveFrom" TIMESTAMP NOT NULL, "gameId" uuid, CONSTRAINT "PK_175177df83f7f392de6251291ee" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_2f55cccc4ab9a41639671072fe" ON "sprocket"."game_rating_config" ("gameId") `);
    await queryRunner.query(`CREATE TABLE "sprocket"."api_token_usage_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "endpoint" character varying NOT NULL, "method" character varying NOT NULL, "statusCode" integer NOT NULL, "ipAddress" character varying NOT NULL, "userAgent" character varying, "wasBlocked" boolean NOT NULL DEFAULT false, "tokenId" uuid, CONSTRAINT "PK_9b8fc8fe574bf0092de60ff15e1" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."api_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "tokenHash" character varying NOT NULL, "tokenPrefix" character varying, "name" character varying NOT NULL, "scopes" text array, "expiresAt" TIMESTAMP, "lastUsedAt" TIMESTAMP, "usageCount" integer NOT NULL DEFAULT '0', "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP, "metadata" jsonb, "userId" uuid, "revokedById" uuid, CONSTRAINT "UQ_b8d5076cd3f3572829943b3f8ad" UNIQUE ("tokenHash"), CONSTRAINT "UQ_d4df579e29383854412151bec34" UNIQUE ("tokenPrefix"), CONSTRAINT "PK_d862311c568d175c26f41bc6f98" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sprocket"."match_players_player" ("matchId" uuid NOT NULL, "playerId" uuid NOT NULL, CONSTRAINT "PK_107b050025f482dbe9076e74838" PRIMARY KEY ("matchId", "playerId"))`);
    await queryRunner.query(`CREATE INDEX "IDX_ab935eb5c2fac329c7ee3decd2" ON "sprocket"."match_players_player" ("matchId") `);
    await queryRunner.query(`CREATE INDEX "IDX_c54b13fd420cbffed15e077610" ON "sprocket"."match_players_player" ("playerId") `);
    await queryRunner.query(`ALTER TABLE "sprocket"."game_mode" ADD CONSTRAINT "FK_1591079e6dddb2d90e90e94fdc2" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."skill_group" ADD CONSTRAINT "FK_71c23df338af5dbf94e453cf53c" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" ADD CONSTRAINT "FK_d9dd6a3d85954577fe57bebbbfe" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" ADD CONSTRAINT "FK_1cdbdafed975ba232472dbdbc0c" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" ADD CONSTRAINT "FK_8d41aae683f387de0d538609907" FOREIGN KEY ("assignedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" ADD CONSTRAINT "FK_1a12eabc4fe270882bf4abe6a7e" FOREIGN KEY ("clubId") REFERENCES "sprocket"."club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" ADD CONSTRAINT "FK_6aeed22b6c00c32108d44dd7d7f" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" ADD CONSTRAINT "FK_28c193edab71b2934f36727351a" FOREIGN KEY ("assignedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club" ADD CONSTRAINT "FK_610d2cffd7621e8407343f74870" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club" ADD CONSTRAINT "FK_0c98255a008d22ed47b424bfff5" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" ADD CONSTRAINT "FK_2d572b5dc481b1a415d2dd6369a" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" ADD CONSTRAINT "FK_8a0de8269ca85c268355057007b" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" ADD CONSTRAINT "FK_71d5c0c7c4e11087183891de211" FOREIGN KEY ("assignedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team" ADD CONSTRAINT "FK_5a5efe782647948e0a62033bf0f" FOREIGN KEY ("clubId") REFERENCES "sprocket"."club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team" ADD CONSTRAINT "FK_0cbb30ed058102b0f260e911e3c" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" ADD CONSTRAINT "FK_6a9b286113e466881b10f2efe9f" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" ADD CONSTRAINT "FK_3033b3764dacc14b2a85591ae96" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" ADD CONSTRAINT "FK_0f202c62bf162e2048e19317ea1" FOREIGN KEY ("seasonId") REFERENCES "sprocket"."season"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" ADD CONSTRAINT "FK_8885cbb33eba6d0f7883565374d" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" ADD CONSTRAINT "FK_d89907ef8bb7f45720a0cfee87f" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" ADD CONSTRAINT "FK_ac49e02bae87a47e3fda059ad58" FOREIGN KEY ("seasonId") REFERENCES "sprocket"."season"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" ADD CONSTRAINT "FK_dd8be69c8a9d2e22ff28b525c7e" FOREIGN KEY ("offeredById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" ADD CONSTRAINT "FK_7687919bf054bf262c669d3ae21" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" ADD CONSTRAINT "FK_7dfdd31fcd2b5aa3b08ed15fe8a" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" ADD CONSTRAINT "FK_622bd2e2975785c536a74754290" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."user_auth_account" ADD CONSTRAINT "FK_6ce330885ba5e40b2a02407d4e7" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."seat" ADD CONSTRAINT "FK_198c4f8d9dbec648ae6e14f62ee" FOREIGN KEY ("roleId") REFERENCES "sprocket"."role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player_stat" ADD CONSTRAINT "FK_9fd193ec8d7668050f0c0a798d4" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player_stat" ADD CONSTRAINT "FK_79f646aeedab99fc9709fb170ce" FOREIGN KEY ("roundId") REFERENCES "sprocket"."round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_stat" ADD CONSTRAINT "FK_40333d55d15efb9469a597afc8b" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_stat" ADD CONSTRAINT "FK_0fc0bb426daf02c46ef57f08c58" FOREIGN KEY ("roundId") REFERENCES "sprocket"."round"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."round" ADD CONSTRAINT "FK_7f3ebe2c9b6582d68973dd1de22" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_877a1f76b4f63193688cc316086" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_8be3d9cb8a809d47b159b0f571b" FOREIGN KEY ("gameModeId") REFERENCES "sprocket"."game_mode"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_0aa844c5090c6363be5cb250ae4" FOREIGN KEY ("homeFranchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_76f603d428780d4725aeeaf4cd0" FOREIGN KEY ("awayFranchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_aac56e10012dbb332933ac51069" FOREIGN KEY ("authorId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" ADD CONSTRAINT "FK_a552a5746921c2f921def8e1feb" FOREIGN KEY ("skillGroupId") REFERENCES "sprocket"."skill_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" ADD CONSTRAINT "FK_6c919ed4d56f6909cfdd55847b6" FOREIGN KEY ("seatId") REFERENCES "sprocket"."seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" ADD CONSTRAINT "FK_8e908c09dac6f44f640772a2332" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" ADD CONSTRAINT "FK_57fec533339e783f49cb0fd752d" FOREIGN KEY ("clubId") REFERENCES "sprocket"."club"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" ADD CONSTRAINT "FK_38f2cca499b86731c73d9ed3678" FOREIGN KEY ("seatId") REFERENCES "sprocket"."seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" ADD CONSTRAINT "FK_9f0682d3e5c8fbeb1591111d085" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" ADD CONSTRAINT "FK_eadf07a54d286dad6f206b1830e" FOREIGN KEY ("franchiseId") REFERENCES "sprocket"."franchise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" ADD CONSTRAINT "FK_42cc926db550620d6f27089cf7e" FOREIGN KEY ("seatId") REFERENCES "sprocket"."seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" ADD CONSTRAINT "FK_1511283821b2b78504bc6d620ff" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" ADD CONSTRAINT "FK_ef41569f6d7f5f49488e8b26b90" FOREIGN KEY ("teamId") REFERENCES "sprocket"."team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."organization_seat_assignment" ADD CONSTRAINT "FK_d090a095cac27b5869ff3e14f2d" FOREIGN KEY ("seatId") REFERENCES "sprocket"."seat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."organization_seat_assignment" ADD CONSTRAINT "FK_508828842622006dfd12a738f4a" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ab40a6f0cd7d3ebfcce082131fd" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_dba55ed826ef26b5b22bd39409b" FOREIGN KEY ("roleId") REFERENCES "role_definition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_f6883010496756ea3e2d980429d" FOREIGN KEY ("assignedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "permission_audit_log" ADD CONSTRAINT "FK_07b3956c539354b05f4589106be" FOREIGN KEY ("actorId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."notification_history" ADD CONSTRAINT "FK_c6149f7c958b143444a8cdb3b52" FOREIGN KEY ("templateId") REFERENCES "sprocket"."notification_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."notification_history" ADD CONSTRAINT "FK_0f4aa9bb533acbeda49fb4f7cd0" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."user_notification_preference" ADD CONSTRAINT "FK_9e2c85e2dface923dfa5ee630e3" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."logs" ADD CONSTRAINT "FK_a1196a1956403417fe3a0343390" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."metrics" ADD CONSTRAINT "FK_592d7eb22e009bb856cc14db1a5" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" ADD CONSTRAINT "FK_1a6e914190b91521922a47b34d9" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" ADD CONSTRAINT "FK_5ca80a6afc0b4c427b5859ea279" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" ADD CONSTRAINT "FK_1070c1b8389b684e920a96a3220" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_timeout" ADD CONSTRAINT "FK_3a26bb814f5dceb3297c4691ff8" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" ADD CONSTRAINT "FK_e381b0d126625bd6814b0e5749a" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" ADD CONSTRAINT "FK_f969c88af895b8cb1783ccae279" FOREIGN KEY ("submittedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" ADD CONSTRAINT "FK_bbea2fc302f809fc09afa6bea2c" FOREIGN KEY ("reviewedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" ADD CONSTRAINT "FK_b306fc19e22aaf61c694dd01261" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" ADD CONSTRAINT "FK_863488c667728b6c7bb80d52a9e" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" ADD CONSTRAINT "FK_ce0905e0865ca4ee0d087917319" FOREIGN KEY ("sourceMatchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" ADD CONSTRAINT "FK_767293e5daf477fb2a14b6b880d" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" ADD CONSTRAINT "FK_929fde69f596d3b6b91febd957f" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" ADD CONSTRAINT "FK_c17bb4fa1db63efcd297816ad8c" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" ADD CONSTRAINT "FK_6ff738bf5f1118410ab64d4c55c" FOREIGN KEY ("inputRatingId") REFERENCES "sprocket"."elo_rating_node"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" ADD CONSTRAINT "FK_8d0f038605305232e1ae5b83538" FOREIGN KEY ("outputRatingId") REFERENCES "sprocket"."elo_rating_node"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."game_rating_config" ADD CONSTRAINT "FK_2f55cccc4ab9a41639671072fe0" FOREIGN KEY ("gameId") REFERENCES "sprocket"."game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token_usage_log" ADD CONSTRAINT "FK_d303775e8a5a89516d3c1060609" FOREIGN KEY ("tokenId") REFERENCES "sprocket"."api_token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token" ADD CONSTRAINT "FK_cbfc4e2b85b78207afb0b2d7fbc" FOREIGN KEY ("userId") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token" ADD CONSTRAINT "FK_a59f074aeeb0d6bf082fb24101c" FOREIGN KEY ("revokedById") REFERENCES "sprocket"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_players_player" ADD CONSTRAINT "FK_ab935eb5c2fac329c7ee3decd2a" FOREIGN KEY ("matchId") REFERENCES "sprocket"."match"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_players_player" ADD CONSTRAINT "FK_c54b13fd420cbffed15e0776107" FOREIGN KEY ("playerId") REFERENCES "sprocket"."player"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
  }
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "sprocket"."game_mode"`);
    await queryRunner.query(`DROP TABLE "sprocket"."skill_group"`);
    await queryRunner.query(`DROP TABLE "sprocket"."game"`);
    await queryRunner.query(`DROP TYPE "sprocket"."franchise_role_roletype_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."franchise_role"`);
    await queryRunner.query(`DROP TABLE "sprocket"."franchise"`);
    await queryRunner.query(`DROP TYPE "sprocket"."club_role_roletype_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."club_role"`);
    await queryRunner.query(`DROP TABLE "sprocket"."club"`);
    await queryRunner.query(`DROP TYPE "sprocket"."team_role_roletype_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."team_role"`);
    await queryRunner.query(`DROP TABLE "sprocket"."team"`);
    await queryRunner.query(`DROP TYPE "sprocket"."season_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."season"`);
    await queryRunner.query(`DROP TYPE "sprocket"."roster_spot_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."roster_spot"`);
    await queryRunner.query(`DROP TYPE "sprocket"."roster_offer_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."roster_offer"`);
    await queryRunner.query(`DROP TABLE "sprocket"."player"`);
    await queryRunner.query(`DROP TYPE "sprocket"."user_auth_account_platform_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."user_auth_account"`);
    await queryRunner.query(`DROP TABLE "sprocket"."user"`);
    await queryRunner.query(`DROP TABLE "sprocket"."role"`);
    await queryRunner.query(`DROP TABLE "sprocket"."seat"`);
    await queryRunner.query(`DROP TABLE "sprocket"."player_stat"`);
    await queryRunner.query(`DROP TABLE "sprocket"."team_stat"`);
    await queryRunner.query(`DROP TABLE "sprocket"."round"`);
    await queryRunner.query(`DROP TYPE "sprocket"."match_status_enum"`);
    await queryRunner.query(`DROP TYPE "sprocket"."match_state_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."match"`);
    await queryRunner.query(`DROP INDEX "sprocket"."IDX_4c90e9976d9356c8d4ec5013ff"`);
    await queryRunner.query(`DROP TABLE "sprocket"."schedule_group"`);
    await queryRunner.query(`DROP TABLE "sprocket"."schedule_group_type"`);
    await queryRunner.query(`DROP TABLE "sprocket"."club_seat_assignment"`);
    await queryRunner.query(`DROP TABLE "sprocket"."franchise_seat_assignment"`);
    await queryRunner.query(`DROP TABLE "sprocket"."team_seat_assignment"`);
    await queryRunner.query(`DROP TABLE "sprocket"."organization_seat_assignment"`);
    await queryRunner.query(`DROP TABLE "casbin_rule"`);
    await queryRunner.query(`DROP TABLE "role_definition"`);
    await queryRunner.query(`DROP TYPE "public"."user_role_status_enum"`);
    await queryRunner.query(`DROP TABLE "user_role"`);
    await queryRunner.query(`DROP TYPE "public"."permission_audit_log_action_enum"`);
    await queryRunner.query(`DROP TABLE "permission_audit_log"`);
    await queryRunner.query(`DROP TYPE "sprocket"."notification_template_channel_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."notification_template"`);
    await queryRunner.query(`DROP TYPE "sprocket"."notification_history_channel_enum"`);
    await queryRunner.query(`DROP TYPE "sprocket"."notification_history_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."notification_history"`);
    await queryRunner.query(`DROP TYPE "sprocket"."user_notification_preference_channel_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."user_notification_preference"`);
    await queryRunner.query(`DROP TABLE "sprocket"."logs"`);
    await queryRunner.query(`DROP TABLE "sprocket"."metrics"`);
    await queryRunner.query(`DROP TYPE "sprocket"."scrim_queue_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."scrim_queue"`);
    await queryRunner.query(`DROP TABLE "sprocket"."scrim_timeout"`);
    await queryRunner.query(`DROP TYPE "sprocket"."match_submission_status_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."match_submission"`);
    await queryRunner.query(`DROP TYPE "public"."event_queue_eventtype_enum"`);
    await queryRunner.query(`DROP TYPE "public"."event_queue_status_enum"`);
    await queryRunner.query(`DROP TYPE "public"."event_queue_targetservice_enum"`);
    await queryRunner.query(`DROP TABLE "event_queue"`);
    await queryRunner.query(`DROP TYPE "sprocket"."elo_rating_node_nodetype_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."elo_rating_node"`);
    await queryRunner.query(`DROP INDEX "sprocket"."IDX_502a69634aabbb35348592bdc4"`);
    await queryRunner.query(`DROP TABLE "sprocket"."match_rating_calculation"`);
    await queryRunner.query(`DROP TYPE "sprocket"."game_rating_config_system_enum"`);
    await queryRunner.query(`DROP TABLE "sprocket"."game_rating_config"`);
    await queryRunner.query(`DROP INDEX "sprocket"."IDX_2f55cccc4ab9a41639671072fe"`);
    await queryRunner.query(`DROP TABLE "sprocket"."api_token_usage_log"`);
    await queryRunner.query(`DROP TABLE "sprocket"."api_token"`);
    await queryRunner.query(`DROP TABLE "sprocket"."match_players_player"`);
    await queryRunner.query(`DROP INDEX "sprocket"."IDX_ab935eb5c2fac329c7ee3decd2"`);
    await queryRunner.query(`DROP INDEX "sprocket"."IDX_c54b13fd420cbffed15e077610"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."game_mode" DROP CONSTRAINT "FK_1591079e6dddb2d90e90e94fdc2"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."skill_group" DROP CONSTRAINT "FK_71c23df338af5dbf94e453cf53c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" DROP CONSTRAINT "FK_d9dd6a3d85954577fe57bebbbfe"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" DROP CONSTRAINT "FK_1cdbdafed975ba232472dbdbc0c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_role" DROP CONSTRAINT "FK_8d41aae683f387de0d538609907"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" DROP CONSTRAINT "FK_1a12eabc4fe270882bf4abe6a7e"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" DROP CONSTRAINT "FK_6aeed22b6c00c32108d44dd7d7f"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_role" DROP CONSTRAINT "FK_28c193edab71b2934f36727351a"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club" DROP CONSTRAINT "FK_610d2cffd7621e8407343f74870"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club" DROP CONSTRAINT "FK_0c98255a008d22ed47b424bfff5"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" DROP CONSTRAINT "FK_2d572b5dc481b1a415d2dd6369a"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" DROP CONSTRAINT "FK_8a0de8269ca85c268355057007b"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_role" DROP CONSTRAINT "FK_71d5c0c7c4e11087183891de211"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team" DROP CONSTRAINT "FK_5a5efe782647948e0a62033bf0f"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team" DROP CONSTRAINT "FK_0cbb30ed058102b0f260e911e3c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" DROP CONSTRAINT "FK_6a9b286113e466881b10f2efe9f"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" DROP CONSTRAINT "FK_3033b3764dacc14b2a85591ae96"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_spot" DROP CONSTRAINT "FK_0f202c62bf162e2048e19317ea1"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" DROP CONSTRAINT "FK_8885cbb33eba6d0f7883565374d"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" DROP CONSTRAINT "FK_d89907ef8bb7f45720a0cfee87f"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" DROP CONSTRAINT "FK_ac49e02bae87a47e3fda059ad58"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."roster_offer" DROP CONSTRAINT "FK_dd8be69c8a9d2e22ff28b525c7e"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" DROP CONSTRAINT "FK_7687919bf054bf262c669d3ae21"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" DROP CONSTRAINT "FK_7dfdd31fcd2b5aa3b08ed15fe8a"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player" DROP CONSTRAINT "FK_622bd2e2975785c536a74754290"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."user_auth_account" DROP CONSTRAINT "FK_6ce330885ba5e40b2a02407d4e7"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."seat" DROP CONSTRAINT "FK_198c4f8d9dbec648ae6e14f62ee"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player_stat" DROP CONSTRAINT "FK_9fd193ec8d7668050f0c0a798d4"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."player_stat" DROP CONSTRAINT "FK_79f646aeedab99fc9709fb170ce"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_stat" DROP CONSTRAINT "FK_40333d55d15efb9469a597afc8b"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_stat" DROP CONSTRAINT "FK_0fc0bb426daf02c46ef57f08c58"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."round" DROP CONSTRAINT "FK_7f3ebe2c9b6582d68973dd1de22"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_877a1f76b4f63193688cc316086"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_8be3d9cb8a809d47b159b0f571b"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_0aa844c5090c6363be5cb250ae4"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_76f603d428780d4725aeeaf4cd0"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_aac56e10012dbb332933ac51069"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match" DROP CONSTRAINT "FK_a552a5746921c2f921def8e1feb"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" DROP CONSTRAINT "FK_6c919ed4d56f6909cfdd55847b6"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" DROP CONSTRAINT "FK_8e908c09dac6f44f640772a2332"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."club_seat_assignment" DROP CONSTRAINT "FK_57fec533339e783f49cb0fd752d"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" DROP CONSTRAINT "FK_38f2cca499b86731c73d9ed3678"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" DROP CONSTRAINT "FK_9f0682d3e5c8fbeb1591111d085"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."franchise_seat_assignment" DROP CONSTRAINT "FK_eadf07a54d286dad6f206b1830e"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" DROP CONSTRAINT "FK_42cc926db550620d6f27089cf7e"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" DROP CONSTRAINT "FK_1511283821b2b78504bc6d620ff"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."team_seat_assignment" DROP CONSTRAINT "FK_ef41569f6d7f5f49488e8b26b90"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."organization_seat_assignment" DROP CONSTRAINT "FK_d090a095cac27b5869ff3e14f2d"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."organization_seat_assignment" DROP CONSTRAINT "FK_508828842622006dfd12a738f4a"`);
    await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ab40a6f0cd7d3ebfcce082131fd"`);
    await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_dba55ed826ef26b5b22bd39409b"`);
    await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_f6883010496756ea3e2d980429d"`);
    await queryRunner.query(`ALTER TABLE "permission_audit_log" DROP CONSTRAINT "FK_07b3956c539354b05f4589106be"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."notification_history" DROP CONSTRAINT "FK_c6149f7c958b143444a8cdb3b52"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."notification_history" DROP CONSTRAINT "FK_0f4aa9bb533acbeda49fb4f7cd0"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."user_notification_preference" DROP CONSTRAINT "FK_9e2c85e2dface923dfa5ee630e3"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."logs" DROP CONSTRAINT "FK_a1196a1956403417fe3a0343390"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."metrics" DROP CONSTRAINT "FK_592d7eb22e009bb856cc14db1a5"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" DROP CONSTRAINT "FK_1a6e914190b91521922a47b34d9"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" DROP CONSTRAINT "FK_5ca80a6afc0b4c427b5859ea279"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_queue" DROP CONSTRAINT "FK_1070c1b8389b684e920a96a3220"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."scrim_timeout" DROP CONSTRAINT "FK_3a26bb814f5dceb3297c4691ff8"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" DROP CONSTRAINT "FK_e381b0d126625bd6814b0e5749a"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" DROP CONSTRAINT "FK_f969c88af895b8cb1783ccae279"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_submission" DROP CONSTRAINT "FK_bbea2fc302f809fc09afa6bea2c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" DROP CONSTRAINT "FK_b306fc19e22aaf61c694dd01261"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" DROP CONSTRAINT "FK_863488c667728b6c7bb80d52a9e"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."elo_rating_node" DROP CONSTRAINT "FK_ce0905e0865ca4ee0d087917319"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" DROP CONSTRAINT "FK_767293e5daf477fb2a14b6b880d"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" DROP CONSTRAINT "FK_929fde69f596d3b6b91febd957f"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" DROP CONSTRAINT "FK_c17bb4fa1db63efcd297816ad8c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" DROP CONSTRAINT "FK_6ff738bf5f1118410ab64d4c55c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_rating_calculation" DROP CONSTRAINT "FK_8d0f038605305232e1ae5b83538"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."game_rating_config" DROP CONSTRAINT "FK_2f55cccc4ab9a41639671072fe0"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token_usage_log" DROP CONSTRAINT "FK_d303775e8a5a89516d3c1060609"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token" DROP CONSTRAINT "FK_cbfc4e2b85b78207afb0b2d7fbc"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."api_token" DROP CONSTRAINT "FK_a59f074aeeb0d6bf082fb24101c"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_players_player" DROP CONSTRAINT "FK_ab935eb5c2fac329c7ee3decd2a"`);
    await queryRunner.query(`ALTER TABLE "sprocket"."match_players_player" DROP CONSTRAINT "FK_c54b13fd420cbffed15e0776107"`);
    await queryRunner.query(`DROP SCHEMA IF EXISTS sprocket CASCADE`);
  }
}
