query Match($submissionId: String!) {
            getMatchBySubmissionId(submissionId: $submissionId) {
                id
                rounds {
                    id
                }
                skillGroup {
                    profile {
                        description
                    }
                }
                gameMode {
                    description
                }
                matchParent {
                    id
                    fixture {
                        scheduleGroup {
                            description
                        }
                        homeFranchise {
                            profile {
                                title
                            }
                        }
                        awayFranchise {
                            profile {
                                title
                            }
                        }
                    }
                }
            }
        }