------------------------
-- Sprocketdb Scripts
------------------------
ALTER TABLE mledb.player_stats
    ALTER start_time TYPE NUMERIC,
    ALTER steering_sensitivity TYPE NUMERIC,
    ALTER end_time TYPE NUMERIC,
    ALTER camera_fov TYPE NUMERIC,
    ALTER camera_height TYPE NUMERIC,
    ALTER camera_pitch TYPE NUMERIC,
    ALTER camera_distance TYPE NUMERIC,
    ALTER camera_stiffness TYPE NUMERIC,
    ALTER camera_swivel_speed TYPE NUMERIC,
    ALTER camera_transition_speed TYPE NUMERIC,
    ALTER boost_per_minute TYPE NUMERIC,
    ALTER boost_collected_per_minute TYPE NUMERIC,
    ALTER boost_average TYPE NUMERIC,
    ALTER boost_collected TYPE NUMERIC,
    ALTER boost_stolen TYPE NUMERIC,
    ALTER boost_collected_big TYPE NUMERIC,
    ALTER boost_stolen_big TYPE NUMERIC,
    ALTER boost_collected_small TYPE NUMERIC,
    ALTER boost_stolen_small TYPE NUMERIC,
    ALTER boost_count_collected_big TYPE NUMERIC,
    ALTER boost_count_stolen_big TYPE NUMERIC,
    ALTER boost_count_collected_small TYPE NUMERIC,
    ALTER boost_count_stolen_small TYPE NUMERIC,
    ALTER boost_overfill TYPE NUMERIC,
    ALTER boost_overfill_stolen TYPE NUMERIC,
    ALTER boost_wasted TYPE NUMERIC,
    ALTER boost_time_empty TYPE NUMERIC,
    ALTER boost_percent_empty TYPE NUMERIC,
    ALTER boost_time_full TYPE NUMERIC,
    ALTER boost_percent_full TYPE NUMERIC,
    ALTER boost_time0to25 TYPE NUMERIC,
    ALTER boost_time25to50 TYPE NUMERIC,
    ALTER boost_time50to75 TYPE NUMERIC,
    ALTER boost_time75to100 TYPE NUMERIC,
    ALTER boost_percent0to25 TYPE NUMERIC,
    ALTER boost_percent25to50 TYPE NUMERIC,
    ALTER boost_percent50to75 TYPE NUMERIC,
    ALTER boost_percent75to100 TYPE NUMERIC,
    ALTER avg_distance_to_ball TYPE NUMERIC,
    ALTER avg_distance_to_ball_possession TYPE NUMERIC,
    ALTER avg_distance_to_ball_no_possession TYPE NUMERIC,
    ALTER avg_distance_to_mates TYPE NUMERIC,
    ALTER time_defensive_third TYPE NUMERIC,
    ALTER time_neutral_third TYPE NUMERIC,
    ALTER time_offensive_third TYPE NUMERIC,
    ALTER time_defensive_half TYPE NUMERIC,
    ALTER time_offensive_half TYPE NUMERIC,
    ALTER time_behind_ball TYPE NUMERIC,
    ALTER time_infront_ball TYPE NUMERIC,
    ALTER time_most_back TYPE NUMERIC,
    ALTER time_most_forward TYPE NUMERIC,
    ALTER goals_against_while_last_defender TYPE NUMERIC,
    ALTER time_closest_to_ball TYPE NUMERIC,
    ALTER time_farthest_from_ball TYPE NUMERIC,
    ALTER percent_defensive_third TYPE NUMERIC,
    ALTER percent_offensive_third TYPE NUMERIC,
    ALTER percent_neutral_third TYPE NUMERIC,
    ALTER percent_defensive_half TYPE NUMERIC,
    ALTER percent_offensive_half TYPE NUMERIC,
    ALTER percent_behind_ball TYPE NUMERIC,
    ALTER percent_infront_ball TYPE NUMERIC,
    ALTER percent_most_back TYPE NUMERIC,
    ALTER percent_most_forward TYPE NUMERIC,
    ALTER percent_closest_to_ball TYPE NUMERIC,
    ALTER percent_farthest_from_ball TYPE NUMERIC,
    ALTER demos_inflicted TYPE NUMERIC,
    ALTER demos_taken TYPE NUMERIC,
    ALTER avg_speed TYPE NUMERIC,
    ALTER total_distance TYPE NUMERIC,
    ALTER time_supersonic_speed TYPE NUMERIC,
    ALTER time_boost_speed TYPE NUMERIC,
    ALTER time_slow_speed TYPE NUMERIC,
    ALTER time_ground TYPE NUMERIC,
    ALTER time_low_air TYPE NUMERIC,
    ALTER time_high_air TYPE NUMERIC,
    ALTER time_powerslide TYPE NUMERIC,
    ALTER count_powerslide TYPE NUMERIC,
    ALTER avg_powerslide_duration TYPE NUMERIC,
    ALTER avg_speed_percentage TYPE NUMERIC,
    ALTER percent_slow_speed TYPE NUMERIC,
    ALTER percent_boost_speed TYPE NUMERIC,
    ALTER percent_supersonic_speed TYPE NUMERIC,
    ALTER percent_ground TYPE NUMERIC,
    ALTER percent_low_air TYPE NUMERIC,
    ALTER percent_high_air TYPE NUMERIC;

ALTER TABLE mledb.team_core_stats
    ALTER COLUMN possession_time TYPE NUMERIC,
        ALTER COLUMN time_in_side TYPE NUMERIC
;


------------------------
-- mledb Scripts
------------------------

ALTER TABLE player_stats
    ALTER COLUMN time_low_air TYPE NUMERIC,
    ALTER COLUMN time_farthest_from_ball TYPE NUMERIC,
    ALTER COLUMN boost_collected_big TYPE NUMERIC,
    ALTER COLUMN time_neutral_third TYPE NUMERIC,
    ALTER COLUMN avg_distance_to_ball_possession TYPE NUMERIC,
    ALTER COLUMN avg_powerslide_duration TYPE NUMERIC,
    ALTER COLUMN percent_offensive_third TYPE NUMERIC,
    ALTER COLUMN boost_time_empty TYPE NUMERIC,
    ALTER COLUMN demos_taken TYPE NUMERIC,
    ALTER COLUMN time_closest_to_ball TYPE NUMERIC,
    ALTER COLUMN time_ground TYPE NUMERIC,
    ALTER COLUMN goals_against_while_last_defender TYPE NUMERIC,
    ALTER COLUMN percent_most_back TYPE NUMERIC,
    ALTER COLUMN time_offensive_third TYPE NUMERIC,
    ALTER COLUMN boost_stolen_small TYPE NUMERIC,
    ALTER COLUMN percent_supersonic_speed TYPE NUMERIC,
    ALTER COLUMN time_behind_ball TYPE NUMERIC,
    ALTER COLUMN percent_high_air TYPE NUMERIC,
    ALTER COLUMN camera_swivel_speed TYPE NUMERIC,
    ALTER COLUMN boost_overfill_stolen TYPE NUMERIC,
    ALTER COLUMN time_boost_speed TYPE NUMERIC,
    ALTER COLUMN boost_wasted TYPE NUMERIC,
    ALTER COLUMN avg_distance_to_ball_no_possession TYPE NUMERIC,
    ALTER COLUMN boost_collected_per_minute TYPE NUMERIC,
    ALTER COLUMN time_slow_speed TYPE NUMERIC,
    ALTER COLUMN boost_stolen_big TYPE NUMERIC,
    ALTER COLUMN boost_time0to25 TYPE NUMERIC,
    ALTER COLUMN time_powerslide TYPE NUMERIC,
    ALTER COLUMN boost_percent50to75 TYPE NUMERIC,
    ALTER COLUMN steering_sensitivity TYPE NUMERIC,
    ALTER COLUMN time_defensive_half TYPE NUMERIC,
    ALTER COLUMN time_defensive_third TYPE NUMERIC,
    ALTER COLUMN boost_collected_small TYPE NUMERIC,
    ALTER COLUMN total_distance TYPE NUMERIC,
    ALTER COLUMN start_time TYPE NUMERIC,
    ALTER COLUMN time_high_air TYPE NUMERIC,
    ALTER COLUMN time_supersonic_speed TYPE NUMERIC,
    ALTER COLUMN percent_low_air TYPE NUMERIC,
    ALTER COLUMN boost_time25to50 TYPE NUMERIC,
    ALTER COLUMN boost_percent_empty TYPE NUMERIC,
    ALTER COLUMN camera_fov TYPE NUMERIC,
    ALTER COLUMN camera_stiffness TYPE NUMERIC,
    ALTER COLUMN percent_defensive_third TYPE NUMERIC,
    ALTER COLUMN time_offensive_half TYPE NUMERIC,
    ALTER COLUMN percent_offensive_half TYPE NUMERIC,
    ALTER COLUMN time_most_forward TYPE NUMERIC,
    ALTER COLUMN boost_collected TYPE NUMERIC,
    ALTER COLUMN time_infront_ball TYPE NUMERIC,
    ALTER COLUMN boost_count_collected_big TYPE NUMERIC,
    ALTER COLUMN percent_infront_ball TYPE NUMERIC,
    ALTER COLUMN boost_overfill TYPE NUMERIC,
    ALTER COLUMN boost_time_full TYPE NUMERIC,
    ALTER COLUMN avg_distance_to_ball TYPE NUMERIC,
    ALTER COLUMN percent_slow_speed TYPE NUMERIC,
    ALTER COLUMN camera_pitch TYPE NUMERIC,
    ALTER COLUMN boost_average TYPE NUMERIC,
    ALTER COLUMN boost_percent0to25 TYPE NUMERIC,
    ALTER COLUMN percent_most_forward TYPE NUMERIC,
    ALTER COLUMN boost_time50to75 TYPE NUMERIC,
    ALTER COLUMN camera_transition_speed TYPE NUMERIC,
    ALTER COLUMN percent_neutral_third TYPE NUMERIC,
    ALTER COLUMN percent_closest_to_ball TYPE NUMERIC,
    ALTER COLUMN avg_speed_percentage TYPE NUMERIC,
    ALTER COLUMN percent_farthest_from_ball TYPE NUMERIC,
    ALTER COLUMN boost_percent75to100 TYPE NUMERIC,
    ALTER COLUMN boost_count_stolen_small TYPE NUMERIC,
    ALTER COLUMN boost_count_collected_small TYPE NUMERIC,
    ALTER COLUMN camera_height TYPE NUMERIC,
    ALTER COLUMN end_time TYPE NUMERIC,
    ALTER COLUMN percent_ground TYPE NUMERIC,
    ALTER COLUMN percent_behind_ball TYPE NUMERIC,
    ALTER COLUMN time_most_back TYPE NUMERIC,
    ALTER COLUMN camera_distance TYPE NUMERIC,
    ALTER COLUMN boost_percent_full TYPE NUMERIC,
    ALTER COLUMN boost_stolen TYPE NUMERIC,
    ALTER COLUMN count_powerslide TYPE NUMERIC,
    ALTER COLUMN avg_speed TYPE NUMERIC,
    ALTER COLUMN percent_boost_speed TYPE NUMERIC,
    ALTER COLUMN avg_distance_to_mates TYPE NUMERIC,
    ALTER COLUMN boost_per_minute TYPE NUMERIC,
    ALTER COLUMN boost_time75to100 TYPE NUMERIC,
    ALTER COLUMN boost_count_stolen_big TYPE NUMERIC,
    ALTER COLUMN boost_percent25to50 TYPE NUMERIC,
    ALTER COLUMN demos_inflicted TYPE NUMERIC,
    ALTER COLUMN percent_defensive_half TYPE NUMERIC;

ALTER TABLE team_core_stats
    ALTER COLUMN possession_time TYPE NUMERIC,
    ALTER COLUMN time_in_side TYPE NUMERIC
;
