api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  docker:
    type: docker_logs
    include_containers:
      - sprocket-lavinmq
      - sprocket-postgres
      - sprocket-web
      - sprocket-core
      - traefik

sinks:
  loki:
    type: loki
    inputs:
      - docker
    endpoint: http://loki:3100
    encoding:
      codec: json
    # labels:
    #   container_id: "{{ container_id }}"
    #   container_name: "{{ container_name }}"