name: run-unit-tests
on:
  pull_request:
    types: [opened,reopened,ready_for_review,synchronize]

jobs:
  run_unit_tests:
    name: Build docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: "Build and execute Test Container"
        shell: bash
        run: |
          docker build . --target=test_image --tag=temp-image;
          docker run --name temp-container temp-image ;

      - name: "Copy Results"
        shell: bash
        if: always()
        run: |
          docker cp temp-container:/app/reports ./results;

      - name: "Clean Up"
        shell: bash
        if: always()
        run: |
          docker rm temp-container;
          docker rmi temp-image;

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            results/**/*.xml
            results/*.xml