config:
  platform:docker-username: gankoji
  platform:docker-access-token:
    secure: AAABADsSgmlJO+PMw4GHrWn2si7h9/n2WylpoUpz7pG8Xmj7uyR5UaSplRoH06Mcpy62TcCjluGTIFUTc1EAdV5gTLCXaqfl
  platform:legacy-image-namespace: minor-league-esports
  platform:image-namespace: sprocketbot
  platform:postgres-username: doadmin
  platform:postgres-port: '25060'
  platform:postgres-host: sprocketbot-postgres-d5033d2-do-user-24528890-0.j.db.ondigitalocean.com
  platform:postgres-password:
    secure: AAABAB7FqFVxkQpGFRis9FDt3+48XS2B9W4QabSxCEvmH7ZrTxl5UlXtuYiHkTkzFw6rYT6hQCU=
  platform:subdomain: 'dev'
  platform:discord-bot-token:
    secure: AAABAA98IbvbeLBDClDyPNetnN5QQyqMfODPRJOPmFgjpC7r8km/WJl+K2I0MCQB+6kUvLw/Dp8en9r9iEnN2MsCRzvLzr8GACT06bHcNLxk2WwJYcQymjoFEPNZe0tt32e/EYCtB28=
  platform:image-tag: main
  platform:legacy-bot-token:
    secure: AAABAAsyhLCoBRrSMGFoGJsEBAVniNvq8nvCsXyhuAQYKn7UurI0QuCDx7Mi8RulDV2frbTOjrIQnfXi+aZIYm9ih2rwcHN2bbuPwzVlkjBIqjWGGEaFNY+9t1TAdy5kFYQ6LVLbVWI=
  platform:hostname: dev.sprocket.mlesports.gg
  platform:server-ip: 192.168.4.39
  platform:tailscale-ip: 100.110.185.84
  platform:platform/discord-bot-token:
    secure: AAABALrtRhPCVbfSozWY5Pleryi2+C5syhIxWwDOOf75pWzETFdWdAsDY4dUSn1ym7kU4ALtrW+CRfunEDiPj8UFYU2lpM8Q+0bf1v5oEGYLYnXP1c8qqY2fIGi9lN7r1rYB7YwiH4U=
  platform:legacy-bot-token-emilio:
    secure: AAABAOrV5e78LSqXujG2bA8sVDVjrckrFTWAJ0BpGdweuF8r81f5NtpKWtlZbun5a25WeQWmxHpgKoysqHAQkUMsQU3rGgvmXs0KDirvB0rFZO70usEpYdULigOUhlrNPlCg21f/
  platform:legacy-bot-token-emilia:
    secure: AAABAEYwlW0pfkmTLCsFZ/uEP77azAMuevwzzGOlzfx2UucwAJg3cxM3xQORNWpXxlLS7KklrkCG/NKuAReH/48e4/hI9kC6LuZArD6MCSD2JDpgGayKE1nqInyU+bX6+hFz7xpC
  platform:postgres-password-legacy:
    secure: AAABALtQ73EGc7NDSYJP+B0YYA3r123+u0vdGBJ3vy1fJqn7lGh9Qh+7oQdWrUy3+8P8lHfjltE=
  platform:google-client-id:
    secure: AAABAAN31wgRDuJElkkTCE3EqAmKTHdslZuyHsKnt/dr8vsoYoxuCGsAFMc5ECBMxPiDMqLN+pSX+loUME4aB79CQ29SZw1maPlPeDi6GhNgN3G4cZm2rheTyfw3FrrgdGr7s6tlnnI=
  platform:google-client-secret:
    secure: AAABANwanQDIY2WWt2lSqdLwlb9hLK/ZiWgE3Ff/9GkagR3bnXgh0HlImXBBsAa9G6OfphJku+IyHhx8YX+b4x545w==
  platform:discord-client-id:
    secure: AAABAD2COy52GyatGtnbJSwyLSqE6c8UI8IEWENfVJbrkpaoG2ek43AwLn3p5TWoXsf4
  platform:discord-client-secret:
    secure: AAABAEqBSPGbOwJNHShrs1aldHZeeJXxhaw0XifEJqvCaxXkJ/4ObmDBnp1nuUJ/QzCLENBzXWB5ot8lAJ9WOw==
  platform:epic-client-id:
    secure: AAABABOWib0al8wZaFEQ7fggptLkQfOxL3EbMmz++UOAx5fe76EJUoZbi4zUIbbialhvW8Md7vCi3sMacRj/g77G9TjrWc+Bqgl9
  platform:epic-client-secret:
    secure: AAABADk+WiwfnoN4eo2o+gD1xgUh4FWPTkZ7sc7S7GRnQUQhZjbuiSyqbQOCZIqrkQ0Xw+kyqluY7Ew4MkSicoaH0Khhu/wkYOkv
  platform:steam-api-key:
    secure: AAABAOG2G6sVIPP++Ma8IlJONm7ZUp4mO/LgrWT6qifuUOH5eDg6
  platform:chatwoot-hmac-key:
    secure: AAABANifT2h2abAL3btzKQ1eEmY+Kax1L+/LoHXVr+0obE/IoylzHQZEaH6t71rzyF05R1MYQSc=
  platform:ballchasing-token:
    secure: AAABAOo3Zd0/27GWYhYn8SVPPKn4lvbjQjOOu2bJK7a722ikS2oyEOHxThPSdjhJNVps8kwYYVgUk+TUC8vc2ggS0/XLJ4r2
  platform:org-team-permission-dual-read: "true"
  platform:layer_1-stack: dev
  platform:layer_2-stack: dev
