import {RocketLeagueMap} from "$mledb";

export const ballchasingMapLookup: Map<string, RocketLeagueMap> = new Map([
    ["arc_p", RocketLeagueMap.STARBASE_ARC],
    ["arc_standard_p", RocketLeagueMap.STARBASE_ARC_STANDARD],
    ["bb_p", RocketLeagueMap.CHAMPIONS_FIELD_NFL],
    ["beach_night_p", RocketLeagueMap.SALTY_SHORES_NIGHT],
    ["beach_p", RocketLeagueMap.SALTY_SHORES],
    ["beachvolley", RocketLeagueMap.SALTY_SHORES_VOLLEYBALL],
    ["chn_stadium_day_p", RocketLeagueMap.FORBIDDEN_TEMPLE_DAY],
    ["chn_stadium_p", RocketLeagueMap.FORBIDDEN_TEMPLE],
    ["cs_day_p", RocketLeagueMap.CHAMPIONS_FIELD_DAY],
    ["cs_hw_p", RocketLeagueMap.RIVALS_ARENA],
    ["cs_p", RocketLeagueMap.CHAMPIONS_FIELD],
    ["eurostadium_night_p", RocketLeagueMap.MANNFIELD_NIGHT],
    ["eurostadium_p", RocketLeagueMap.MANNFIELD],
    ["eurostadium_rainy_p", RocketLeagueMap.MANNFIELD_STORMY],
    ["eurostadium_snownight_p", RocketLeagueMap.MANNFIELD_SNOWY],
    ["farm_night_p", RocketLeagueMap.FARMSTEAD_NIGHT],
    ["farm_p", RocketLeagueMap.FARMSTEAD],
    ["farm_upsidedown_p", RocketLeagueMap.FARMSTEAD_UPSIDE_DOWN],
    ["haunted_trainstation_p", RocketLeagueMap.URBAN_CENTRAL_HAUNTED],
    ["hoopsstadium_p", RocketLeagueMap.DUNK_HOUSE],
    ["music_p", RocketLeagueMap.NEON_FIELDS],
    ["neotokyo_p", RocketLeagueMap.NEO_TOKYO],
    ["neotokyo_standard_p", RocketLeagueMap.NEO_TOKYO_STANDARD],
    ["park_night_p", RocketLeagueMap.BECKWITH_PARK_MIDNIGHT],
    ["park_p", RocketLeagueMap.BECKWITH_PARK],
    ["park_rainy_p", RocketLeagueMap.BECKWITH_PARK_STORMY],
    ["shattershot_p", RocketLeagueMap.CORE_707],
    ["stadium_day_p", RocketLeagueMap.DFH_STADIUM_DAY],
    ["stadium_foggy_p", RocketLeagueMap.DFH_STADIUM_STORMY],
    ["stadium_p", RocketLeagueMap.DFH_STADIUM],
    ["stadium_race_day_p", RocketLeagueMap.DFH_STADIUM_CIRCUIT],
    ["stadium_winter_p", RocketLeagueMap.DFH_STADIUM_SNOWY],
    ["throwbackstadium_p", RocketLeagueMap.THROWBACK],
    ["trainstation_dawn_p", RocketLeagueMap.URBAN_CENTRAL_DAWN],
    ["trainstation_night_p", RocketLeagueMap.URBAN_CENTRAL_NIGHT],
    ["trainstation_p", RocketLeagueMap.URBAN_CENTRAL],
    ["underwater_p", RocketLeagueMap.AQUADOME],
    ["utopiastadium_dusk_p", RocketLeagueMap.UTOPIA_COLISEUM_DUSK],
    ["utopiastadium_p", RocketLeagueMap.UTOPIA_COLISEUM],
    ["utopiastadium_snow_p", RocketLeagueMap.UTOPIA_COLISEUM_SNOWY],
    ["wasteland_night_p", RocketLeagueMap.WASTELAND_NIGHT],
    ["wasteland_night_s_p", RocketLeagueMap.WASTELAND_STANDARD_NIGHT],
    ["wasteland_p", RocketLeagueMap.WASTELAND],
    ["wasteland_s_p", RocketLeagueMap.WASTELAND_STANDARD],
]);
