name: Build Sprocket Container
description: "Builds and pushes a Sprocket Container to docker hub"
  
inputs:
  build_directory:
    description: "Path in the monorepo to use as root"
    required: true
  docker_image:
    description: "Name of the image to build"
    required: true
  docker_tag:
    description: "Tag for the image to build (usually branch name)"
    required: true
  docker_username:
    description: "Username for hub.docker.com"
    required: true
  docker_access_token:
    description: "Access token for hub.docker.com"
    required: true
  discord_webhook:
    description: "Webhook URL to send status updates"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_access_token }}

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: sprocket-core
        path: /tmp

    - name: Load image
      shell: sh
      run: |
        docker load --input /tmp/core.tar;
        docker images;

    - name: Build And Push Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.build_directory }}
        file: ${{ inputs.build_directory }}/Dockerfile
        target: app_image
        push: true
        tags: ${{inputs.docker_username}}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}
        platforms: linux/amd64
    
    - uses: sarisia/actions-status-discord@v1
      if: startsWith( inputs.discord_webhook, 'https' )
      with:
        webhook: ${{ inputs.discord_webhook }}
        