import {z} from "zod";

export const BallchasingPlayerStatsSchema = z.object({
    core: z.object({
        mvp: z.boolean().default(false),
        goals: z.number().default(0),
        saves: z.number().default(0),
        score: z.number().default(0),
        shots: z.number().default(0),
        assists: z.number().default(0),
        goals_against: z.number().default(0),
        shots_against: z.number().default(0),
        shooting_percentage: z.number().default(0),
    }),
    demo: z.object({
        taken: z.number().default(0),
        inflicted: z.number().default(0),
    }),
    boost: z.object({
        bpm: z.number().default(0),
        bcpm: z.number().default(0),
        avg_amount: z.number().default(0),
        amount_stolen: z.number().default(0),
        amount_overfill: z.number().default(0),
        time_boost_0_25: z.number().default(0),
        time_full_boost: z.number().default(0),
        time_zero_boost: z.number().default(0),
        amount_collected: z.number().default(0),
        count_stolen_big: z.number().default(0),
        time_boost_25_50: z.number().default(0),
        time_boost_50_75: z.number().default(0),
        amount_stolen_big: z.number().default(0),
        time_boost_75_100: z.number().default(0),
        count_stolen_small: z.number().default(0),
        percent_boost_0_25: z.number().default(0),
        percent_full_boost: z.number().default(0),
        percent_zero_boost: z.number().default(0),
        amount_stolen_small: z.number().default(0),
        count_collected_big: z.number().default(0),
        percent_boost_25_50: z.number().default(0),
        percent_boost_50_75: z.number().default(0),
        amount_collected_big: z.number().default(0),
        percent_boost_75_100: z.number().default(0),
        count_collected_small: z.number().default(0),
        amount_collected_small: z.number().default(0),
        amount_overfill_stolen: z.number().default(0),
        amount_used_while_supersonic: z.number().default(0),
    }),
    movement: z.object({
        avg_speed: z.number().default(0),
        time_ground: z.number().default(0),
        time_low_air: z.number().default(0),
        time_high_air: z.number().default(0),
        percent_ground: z.number().default(0),
        total_distance: z.number().default(0),
        percent_low_air: z.number().default(0),
        time_powerslide: z.number().default(0),
        time_slow_speed: z.number().default(0),
        count_powerslide: z.number().default(0),
        percent_high_air: z.number().default(0),
        time_boost_speed: z.number().default(0),
        percent_slow_speed: z.number().default(0),
        percent_boost_speed: z.number().default(0),
        avg_speed_percentage: z.number().default(0),
        time_supersonic_speed: z.number().default(0),
        avg_powerslide_duration: z.number().default(0),
        percent_supersonic_speed: z.number().default(0),
    }),
    positioning: z.object({
        time_most_back: z.number().default(0),
        time_behind_ball: z.number().default(0),
        percent_most_back: z.number().default(0),
        time_infront_ball: z.number().default(0),
        time_most_forward: z.number().default(0),
        time_neutral_third: z.number().default(0),
        percent_behind_ball: z.number().default(0),
        time_defensive_half: z.number().default(0),
        time_offensive_half: z.number().default(0),
        avg_distance_to_ball: z.number().default(0),
        percent_infront_ball: z.number().default(0),
        percent_most_forward: z.number().default(0),
        time_closest_to_ball: z.number().default(0),
        time_defensive_third: z.number().default(0),
        time_offensive_third: z.number().default(0),
        avg_distance_to_mates: z.number().default(0),
        percent_neutral_third: z.number().default(0),
        percent_defensive_half: z.number().default(0),
        percent_offensive_half: z.number().default(0),
        percent_closest_to_ball: z.number().default(0),
        percent_defensive_third: z.number().default(0),
        percent_offensive_third: z.number().default(0),
        time_farthest_from_ball: z.number().default(0),
        percent_farthest_from_ball: z.number().default(0),
        avg_distance_to_ball_possession: z.number().default(0),
        goals_against_while_last_defender: z.number().default(0),
        avg_distance_to_ball_no_possession: z.number().default(0),
    }),
});
export type BallchasingPlayerStats = z.infer<typeof BallchasingPlayerStatsSchema>;

export const BallchasingPlayerSchema = z.object({
    id: z.object({
        id: z.string(),
        platform: z.enum(["steam", "xbox", "ps4", "epic"]),
    }),
    name: z.string(),
    camera: z.object({
        fov: z.number(),
        pitch: z.number(),
        height: z.number(),
        distance: z.number(),
        stiffness: z.number(),
        swivel_speed: z.number(),
        transition_speed: z.number(),
    }),
    car_id: z.number().default(-1),
    car_name: z.string().default("UNKNOWN"),
    end_time: z.number(),
    start_time: z.number(),
    steering_sensitivity: z.number(),

    stats: BallchasingPlayerStatsSchema,
});
export type BallchasingPlayer = z.infer<typeof BallchasingPlayerSchema>;
