query ScrimPageRoot {
	whoami {
		players { id }
	}
	currentScrim @Player_delete {
		...ScrimFlow_Fragment
		id
		state
		complete
	}
	pendingScrims @list(name: "ScrimPage_PendingScrims") {
		...ScrimList_Fragment
		id
		state
		participants {
			id
			checkedIn
		}
		participantCount
		complete
	}
}
