query CreateScrimData {
    whoami {
        players {
            game {
                name
                id
                gameModes {
                    id
                    name
                }
            }
        }
    }
	# games {
	# 	name
	# 	id
    #     gameModes {
    #         id
    #         name
    #     }
	# }
}
