import * as docker from '@pulumi/docker';
import { HOSTNAME } from '../../../constants';
const DATABASE_HOST = "airbyte-db"
const WORKER_ENVIRONMENT = "docker";
const DATABASE_USER = "docker"
const DATABASE_PASSWORD = "docker"
const DATABASE_URL = `jdbc:postgresql://${DATABASE_HOST}:5432/airbyte`
export const AIRBYTE_VERSION = '0.40.4'

export const initEnv = {
  LOCAL_ROOT: '/tmp/airbyte_local',
  HACK_LOCAL_ROOT_PARENT: '/tmp'
};

export const dbEnv = {
  DATABASE_PASSWORD: DATABASE_PASSWORD,
  DATABASE_URL: DATABASE_URL,
  DATABASE_USER: DATABASE_USER,
  POSTGRES_PASSWORD: DATABASE_PASSWORD,
  POSTGRES_USER: DATABASE_USER,
}

export const bootloaderEnv = {
  AIRBYTE_VERSION: AIRBYTE_VERSION,
  LOG_LEVEL: 'INFO',
  RUN_DATABASE_MIGRATION_ON_STARTUP: '',
  DATABASE_PASSWORD: DATABASE_PASSWORD,
  DATABASE_URL: DATABASE_URL,
  DATABASE_USER: DATABASE_USER,
}


const TEMPORAL_HOST = "airbyte-temporal:7233";
const WEBAPP_URL = `https://airbyte.${HOSTNAME}:443`;
const WORKSPACE_ROOT = "/tmp/workspace";
export const workerEnv = {
  AIRBYTE_VERSION: AIRBYTE_VERSION,
  AUTO_DISABLE_FAILING_CONNECTIONS: "false",
  CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: "0.35.15.001",
  CONFIG_ROOT: "/data",
  DATABASE_PASSWORD: DATABASE_PASSWORD,
  DATABASE_URL: DATABASE_URL,
  DATABASE_USER: DATABASE_USER,
  INTERNAL_API_HOST: "airbyte-server:8001",
  JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: "0.29.15.001",
  LOCAL_DOCKER_MOUNT: "/tmp/airbyte_local",
  LOCAL_ROOT: "/tmp/airbyte_local",
  LOG_LEVEL: "INFO",
  MAX_CHECK_WORKERS: "5",
  MAX_DISCOVER_WORKERS: "5",
  MAX_SPEC_WORKERS: "5",
  MAX_SYNC_WORKERS: "5",
  SECRET_PERSISTENCE: "NONE",
  SYNC_JOB_MAX_ATTEMPTS: "3",
  SYNC_JOB_MAX_TIMEOUT_DAYS: "3",
  TEMPORAL_HOST: TEMPORAL_HOST,
  WEBAPP_URL: WEBAPP_URL,
  WORKER_ENVIRONMENT: WORKER_ENVIRONMENT,
  WORKSPACE_DOCKER_MOUNT: "airbyte_workspace",
  WORKSPACE_ROOT: WORKSPACE_ROOT,
  JOB_ERROR_REPORTING_STRATEGY: "logging",
  USE_STREAM_CAPABLE_STATE: "true",
}

export const cronEnv = {
  DB: "postgresql",
  DB_PORT: "5432",
  LOG_LEVEL: "INFO",
  POSTGRES_PWD: DATABASE_PASSWORD,
  POSTGRES_SEEDS: DATABASE_HOST,
  POSTGRES_USER: DATABASE_USER,
  WORKSPACE_ROOT: WORKSPACE_ROOT,
}

export const temporalEnv = {
  DB: "postgresql",
  DB_PORT: "5432",
  DYNAMIC_CONFIG_FILE_PATH: "config/dynamicconfig/development.yaml",
  LOG_LEVEL: "INFO",
  POSTGRES_PWD: DATABASE_PASSWORD,
  POSTGRES_SEEDS: DATABASE_HOST,
  POSTGRES_USER: DATABASE_USER,
}

export const webappEnv = {
  TRACKING_STRATEGY: "segment",
  AIRBYTE_VERSION: AIRBYTE_VERSION,
  API_URL: "/api/v1/",
  INTERNAL_API_HOST: "airbyte-server:8001",
}

export const serverEnv = {
  AIRBYTE_VERSION: AIRBYTE_VERSION,
  CONFIG_ROOT: "/data",
  DATABASE_PASSWORD: DATABASE_PASSWORD,
  DATABASE_URL: DATABASE_URL,
  DATABASE_USER: DATABASE_USER,
  JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: "0.29.15.001",
  CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION: "0.35.15.001",
  LOG_LEVEL: "INFO",
  SECRET_PERSISTENCE: "NONE",

  TEMPORAL_HOST: TEMPORAL_HOST,
  JOB_ERROR_REPORTING_STRATEGY: "logging",
  WEBAPP_URL: WEBAPP_URL,
  WORKER_ENVIRONMENT: WORKER_ENVIRONMENT,
  WORKSPACE_ROOT: WORKSPACE_ROOT,
}
