name: Check Linting/Formatting

on:
  pull_request:
    branches: [dev, staging, main, "epic/web-rewrite-2"]

jobs:
  lint-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint:check