query CreateScrimData {
    whoami {
        players {
            game {
                name
                id
                gameModes {
                    id
                    name
                }
            }
        }
    }
}
